name = "Paragon Game"
uid = "BREWLANS-22b4-4936-820e-PARAGON00191"
version = 1.91
copyright = "© 2012 - 2015 Sean Wheeldon"
description = "Few vs Many. The few get a Paragon and a SACU each. Only they can build new Paragons and can always build one, regardless of race."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_Gameplay/ParagonGame/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { "6EAA2403-27A8-47ee-B4DF-5017E056E501" }
before = { }
after = { }
