name = "Paragon Game"
uid = "BREWLANS-22b4-4936-820e-PARAGON0040"
version = 4
copyright = "© 2012–2020 Sean Wheeldon"
description = "Player(s) on the smallest team(s) spawn with a Paragon and a SACU. Everyone gets that if teams are unlocked."
author = "Balthazar"
icon = "/mods/BrewLAN_Gameplay/ParagonGame/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { "6EAA2403-27A8-47ee-B4DF-5017E056E501" }
before = { }
after = { }
