name = "Wonky Resources"
uid = "f31a09b5-2b2f-4bb4-aeac-resource0000001"
version = 1
copyright = "© 2021 Sean Wheeldon"
description = "Structures built on resource points no longer care about the terrain flatness, and tilt to match the terrain if BrewLAN is enabled."
author = "Balthazar"
icon = "/mods/BrewLAN_Gameplay/WonkyResources/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
