name = "BrewLAN UI: Spawn Menu"
uid = "25D57D85-7D84-27HT-A501-BR3WUISM00002"
version = 0.2
copyright = "© 2020 Seaan Wheeldon"
description = "Gives the ALT-F2 cheatspawn menu mod filters. Functions on any version of Supreme Commander or Forged Alliance."
author = "Balthazar"
icon = "/mods/BrewLAN/modules/BrewUI/spawnmenu/BrewUI.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
conflicts = {  }
before = {  }
after = {  }
