name = "BrewLAN UI: Spawn Menu"
uid = "25D57D85-7D84-27HT-A501-BR3WUISM00001"
version = 0.1
copyright = "© Various"
description = "Replaces the ALT-F2 cheatspawn menu. Functions on any version of Supreme Commander or Forged Alliance."
author = "Balthazar"
icon = "/mods/BrewLAN/modules/BrewUI/engineertab/BrewUI.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
conflicts = {  }
before = {  }
after = {  }
