--ISO_639-1_code=IT
--Translated by: Google
CityscapesSpawn_LOB="Cityscapes: giocatore slot"
CityscapesSpawn_LOB_D="Definisce quali località dei luoghi di studio del giocatore possono generare le città."
CityscapesSpawn_LOB_EmptySpots="Slot vuoti"
CityscapesSpawn_LOB_EmptySpotsD="Le città possono generare in luoghi di spawn del giocatore vuoto."
CityscapesSpawn_LOB_AllSlots="Tutte le slot."
CityscapesSpawn_LOB_AllSlotsD="Le città possono generare in qualsiasi luoghi di studio del giocatore."
CityscapesSpawn_LOB_OccupiedSlots="Slot occupati"
CityscapesSpawn_LOB_OccupiedSlotsD="Le città possono generare attorno ai giocatori."
CityscapesSpawn_LOB_false="Nessuna slot."
CityscapesSpawn_LOB_falseD="Le città non si generano nella posizione del budello del giocatore."

CityscapesTeam_LOB="Cityscapes: Player Slot Team"
CityscapesTeam_LOB_D="Definisce il proprietario delle città generato in slot occupati, se esistono."
CityscapesTeam_LOB_Civilian="Civile"
CityscapesTeam_LOB_CivilianD="Le città in slot occupati sono controllati civili."
CityscapesTeam_LOB_LocalArmy="Esercito locale"
CityscapesTeam_LOB_CivilianD="Le città in slot occupati sono controllate da quell'esercito."

CityscapesExpansion_LOB="Cityscapes: zone di espansione"
CityscapesExpansion_LOB_D="Determina se le città generano gli indicatori di zone di espansione."
CityscapesExpansion_LOB_Enabled="Abilitato"
CityscapesExpansion_LOB_EnabledD="Le città civili generano i marcatori di espansione."
CityscapesExpansion_LOB_Disabled="Disabilitato"
CityscapesExpansion_LOB_DisabledD="Nessuna città generata a marcatori di espansione."

CityscapesLargeExpansion_LOB="Cityscapes: ampie zone di espansione"
CityscapesLargeExpansion_LOB_D="Determina se le città si generano in qualsiasi grande marcatrice di zone di espansione."
CityscapesLargeExpansion_LOB_Enabled="Abilitato"
CityscapesLargeExpansion_LOB_EnabledD="Le città civili si generano a grandi marcatori di espansione."
CityscapesLargeExpansion_LOB_Disabled="Disabilitato"
CityscapesLargeExpansion_LOB_DisabledD="Nessuna città generata a grandi marcatori di espansione."

CityscapesObjective_LOB="Cityscapes: marcatori oggettivi"
CityscapesObjective_LOB_D="Determina se le città si generano in qualsiasi marcatore oggettivo."
CityscapesObjective_LOB_Enabled="Abilitato"
CityscapesObjective_LOB_EnabledD="Le città civili si generano a marcatori oggettivi."
CityscapesObjective_LOB_Disabled="Disabilitato"
CityscapesObjective_LOB_DisabledD="Nessuna città generata a marcatori oggettivi."
