--ISO_639-1_code=IT
--Translated by: Google
CityscapesSpawn_LOB="Cityscapes: giocatore di slot"
CityscapesSpawn_LOB_D="Definisce quali posizioni giocatore di spawn città possono deporre le uova a."
CityscapesSpawn_LOB_EmptySpots="slot vuoti"
CityscapesSpawn_LOB_EmptySpotsD="Le città possono deporre le uova in luoghi vuoti giocatore di spawn."
CityscapesSpawn_LOB_AllSlots="tutti gli slot"
CityscapesSpawn_LOB_AllSlotsD="Le città possono deporre le uova in qualsiasi luogo lettore deporre le uova."
CityscapesSpawn_LOB_OccupiedSlots="slot occupati"
CityscapesSpawn_LOB_OccupiedSlotsD="Le città possono deporre le uova in giro giocatori."
CityscapesSpawn_LOB_false="No Slot"
CityscapesSpawn_LOB_falseD="Le città non si riproducono nella posizione lettore deporre le uova."

CityscapesTeam_LOB="Cityscapes: Player Slot Squadra"
CityscapesTeam_LOB_D="Definisce il proprietario di città generate negli slot occupati, se esistono."
CityscapesTeam_LOB_Civilian="Civile"
CityscapesTeam_LOB_CivilianD="Città in slot occupati sono civili controllata."
CityscapesTeam_LOB_LocalArmy="Army locale"
CityscapesTeam_LOB_CivilianD="Città in slot occupati sono controllati da quell'esercito."

CityscapesExpansion_LOB="Paesaggi: zone di espansione"
CityscapesExpansion_LOB_D="Determina se le città depongono le uova in zone di espansione marcatori."
CityscapesExpansion_LOB_Enabled="Abilitato"
CityscapesExpansion_LOB_EnabledD="le città civili depongono le uova a marcatori di espansione."
CityscapesExpansion_LOB_Disabled="Disabilitato"
CityscapesExpansion_LOB_DisabledD="Non ci sono città depongono le uova a marcatori di espansione."

CityscapesLargeExpansion_LOB="Cityscapes: Grandi zone di espansione"
CityscapesLargeExpansion_LOB_D="Determina se le città depongono le uova in tutte le grandi zone di espansione marcatori."
CityscapesLargeExpansion_LOB_Enabled="Abilitato"
CityscapesLargeExpansion_LOB_EnabledD="le città civili depongono le uova nei grandi marcatori di espansione."
CityscapesLargeExpansion_LOB_Disabled="Disabilitato"
CityscapesLargeExpansion_LOB_DisabledD="Non ci sono città depongono le uova nei grandi marcatori di espansione."

CityscapesObjective_LOB="Cityscapes: segnalini obiettivo"
CityscapesObjective_LOB_D="Determina se le città depongono le uova in qualsiasi segnalini obiettivo."
CityscapesObjective_LOB_Enabled="Abilitato"
CityscapesObjective_LOB_EnabledD="le città civili depongono le uova a segnalini obiettivo."
CityscapesObjective_LOB_Disabled="Disabilitato"
CityscapesObjective_LOB_DisabledD="Non ci sono città depongono le uova a segnalini obiettivo."