name = "BrewUI 0.1"
uid = "25D57D85-7D84-27HT-A501-BR3WUI0000001"
version = "0.1"
copyright = "2009 - 2014 Sean Wheeldon"
description = "Interface changes for BrewLAN. Dont run without BrewLAN. Will conflict with any mod with a \"/hook/lua/ui/game/avatars.lua\" file."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN/documentation/icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = true
conflicts = {  }
before = {  }
after = {  }
