name = "Crystal Hill"
uid = "BREWLANS-22b4-4936-820e-CRYSTAL00017"
version = 1.7
copyright = "© 2014–2018 Sean Wheeldon"
description = "King of the Hill with crystals. Spawns a crystal in the middle of the map. Capture it and keep it to win."
author = "Balthazar"
icon = "/mods/BrewLAN_Gameplay/CrystalHill/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { "6EAA2403-27A8-47ee-B4DF-5017E056E501",}
before = { }
after = { }
