name = "Spomeniki"
uid = "BREWLANS-a0a7-426d-88f2-SPOMEN00000"
version = 0
copyright = "© 2018 Sean Wheeldon"
description = "How Soviet of you."
author = "Balthazar"
icon = "/mods/BrewLAN_Plenae/Spomeniki/Spomeniki.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }
