name = "Tech Level Randomiser"
uid = "25D57D85-7D84-27HT-A502-TECHRND00000"
version = 0
copyright = "© 2019 Sean Wheeldon"
description = "Units are randomly swapped between tech levels within each faction. WARNING: May make game strategically unplayable."
author = "Balthazar"
selectable = true
enabled = true
exclusive = false
ui_only = false
