bair0105="Light Gunship"
baa0105_name="Respirer"
bea0105_name="Pigeon"
bsa0105_name="Vulesel"
Unit_Description_BrewLAN_T1A001="Light Guship. Primary role is base defence. Effective against low-level ground units."
Unit_Description_BrewLAN_T1A002="Light Guship. Effective against low-level ground units. Equipped with a light transport hook."
Unit_Description_BrewLAN_T1A003="Light Guship. Primary role is base defence. Effective against low-level ground units."

bair0106="Light Torpedo Bomber"
baa0106_name="Saksinokka"
bea0106_name="Seagull"
bra0106_name="Gannet"
bsa0106_name="Sou-ioz"
Unit_Description_BrewLAN_T1A004="Torpedo bomber. Designed to engage low-level naval units."

bbui2103="Light Artillery Installation"
bab2303_name="Charis"
beb2103_name="Poker"
brb2303_name="Little Bertha"
bsb2303_name="Thaam-atha"
Unit_Description_BrewLAN_T1D001="Light stationary artillery. Designed to engage low to mid-level units."

Unit_Description_BrewLAN_T1P001="Generates a protective shield around units and structures within its radius."
Unit_Description_BrewLAN_T1P002="Generates a protective shield around units and structures within its radius."
Unit_Description_BrewLAN_T1P003="Generates a protective shield around units and structures within its radius. Upradable twice."
Unit_Description_BrewLAN_T1U001="Light air staging facility. Repairs and refuels aircraft small aircraft, one landing pad."

Unit_Description_BrewLAN_T2R001="Stores large amounts of energy. Construct next to power generators for adjacency bonus."
Unit_Description_BrewLAN_T2R002="Stores large amounts of mass. Construct next to extractors or fabricators for adjacency bonus."
Unit_Description_BrewLAN_T2D001="An all-terrain medium damage proximity mine system. Visible only to Omni."
Unit_Description_BrewLAN_T2D002="Generates a protective shield around units and structures within its radius. Shield can be upgraded three times."
Unit_Description_BrewLAN_T2D002="Generates a heavy shield around units and structures within its radius."

Unit_Description_BrewLAN_T3A001="Heavy gunship. Armed with Phasic autoguns and powerful but short range AA weaponry."
bsa0305_name="Vulthuum"
bsa0305_desc="Heavy Gunship"
bsa0305_help="Heavy Gunship"
Unit_Description_BrewLAN_T3A002="Heavy air transport. Armed with heavy anti-air defence, an EMP weapon and a stealth field. Can carry up to 16 units."
Unit_Description_BrewLAN_T3A003="Heavy air transport. Features 32 transportation clamps, heavy weaponry and a shield generator. Can carry up to 32 units."
Unit_Description_BrewLAN_T3A004="Heavy air transport. Feaures an all-targetting insta-kill lazor, 3000 unit clams and an engraving of your mother."
baa0306_name="Cirrus"
baa0306_desc="Heavy Air Transport"
baa0306_help="Heavy Air Transport"
bra0306_name="Night Skimmer"
bra0306_desc="Heavy Air Transport"
bra0306_help="Heavy Air Transport"
bsa0306_name="Vishuum"
bsa0306_desc="Heavy Air Transport"
bsa0306_help="Heavy Air Transport"
Unit_Description_BrewLAN_T3A005="High-level stealth torpedo bomber. Designed to engage high-level naval units and overwelm torpedo defences with large salvos."

Unit_Description_BrewLAN_T3L001="Shielded Siege assault bot. Armed with dual Aire-au Bolters."
Unit_Description_BrewLAN_T3L002="Heavily armored assault tank. Low rate of fire, designed as a heavy support unit."
Unit_Description_BrewLAN_T3B001="Heavy defensive tower. Attacks land- and sea-based units with a powerful sweeping laser. Does not engage aircraft or submerged units."
Unit_Description_BrewLAN_T3B002="Satellite-based observation system. Has a wide line-of-sight and omni censors. If its control center is destroyed, the satelite is immediately disabled."

Unit_Description_BrewLAN_T4B001="Slightly broken experimental point defence. Effectively an immobile fatboy. Wont fire westward."
Unit_Description_BrewLAN_T4B002="Experimental rapid-fire artillery. Consumes massive amounts of Energy with each shot."