name = "Debug Tools"
uid = "2529ea71-93ef-41a6-b552-LOGS0000000009"
version = 0.9
copyright = "© 2017–2018 Sean Wheeldon"
description = "Debug and testing tools. Not for real matches."
author = "Balthazar"
--icon = "/mods/BrewLAN_Plenae/ExperimentalIcons/Experimental-Icon-Overhaul_Mod_Icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
