name = "Expert Camo"
uid = "2529ea71-93ef-41a6-b552-CAMMO000000010"
version = 1
copyright = "© 2017–2018 Sean Wheeldon"
description = "Provides framework support for quickly generated reskins of units in mod folders 'TerrainMeshes' and 'CustomMeshes'."
author = "Sean 'Balthazar' Wheeldon"
icon = "/mods/BrewLAN_Plenae/ExpertCamo/Mod_Icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
