name = "BrewLAN: Caffe Corretto"
uid = "25D57D85-9JA7-D842-BREW-TURRETS000004"
version = 0.4
copyright = "© 2017–2022 Sean Wheeldon"
description = "Coffee with a shot; adds turrets and buff nodes. All units built by BrewLAN field engineers."
author = "Balthazar"
icon = "/mods/BrewLAN_Units/BrewTurrets/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }
