name = "Caffe Corretto"
uid = "25D57D85-9JA7-D842-BREW-TURRETS000001"
version = 0.1
copyright = "© 2017 Sean Wheeldon"
description = "Coffee with a shot; adds turrets and weapon nodes. All units built by BrewLAN field engineers."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_Units/BrewTurrets/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
