name = "Waterlag"
uid = "25D57D85-9JA7-D842-GKG4-ASJDKG49G8S49"
version = "0.1a"
copyright = "2009 Sean Wheeldon"
description = "Adds aquatic abilities to each building that isn't a factory, wall, silo, or experimental."
author = "Sean Wheeldon"
icon = "/mods/waterlag/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = {
}before = { }
after = { }
