name = "Cost Variance"
uid = "1a17998a-7355-11e5-8bcf-feff819cdc9f"
version = 0.0
copyright = "© 2015 Sean Wheeldon"
description = "Randomly alters the build costs of all non-economic units, and alters other stats to match."
author = "Sean Wheeldon"
--icon = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = {
}before = { }
after = { }
