name = "Crystal Hill"
uid = "BREWLANS-22b4-4936-820e-CRYSTAL00014"
version = 1.4
copyright = "2014-2015 Sean Wheeldon"
description = "King of the Hill with crystals. Spawns a crystal in the middle of the map. Capture it and keep it to win."
author = "Sean Wheeldon"
icon = "/mods/CrystalHill/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { "6EAA2403-27A8-47ee-B4DF-5017E056E501",}
before = { }
after = { }
