name = "BrewLAN: Tea Party"
uid = "25D57D85-9JA7-D842-BREW-BOATS00000001"
version = 1
copyright = "© 2020–2020 Sean Wheeldon"
description = "Adds an Aeon Experimental Battlecruiser."
author = "Balthazar"
icon = "/mods/BrewLAN_Units/BrewTeaParty/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
