name = "Damage Numbers"
uid = "25D57D85-9JA7-D842-GKG4-DAMAGENO00000"
version = 0.0
copyright = "© 2017–2018 Sean Wheeldon"
description = "Damage numbers appear."
author = "Balthazar"
icon = "/mods/BrewLAN_Plenae/DamageNumbers/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = {
}before = { }
after = { }
