name = "BrewLAN UI: Engineer Tab"
uid = "25D57D85-7D84-27HT-A501-BR3WUIET00003"
version = 0.3
copyright = "© 2009–2019 Sean Wheeldon"
description = "Adds field engineers to the engineer tab. Self-disables without BrewLAN active. Will conflict with other engineer tab mods."
author = "Balthazar"
icon = "/mods/BrewLAN/modules/BrewUI/engineertab/BrewUI.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
conflicts = {  }
before = {  }
after = {  }
