name = "Pulchritudinousity"
uid = "BREWLANS-a0a7-426d-88f2-PHOTORZ00001"
version = 0
copyright = "2015 Sean Wheeldon"
description = "Various tweeks designed for taking better screenshots. Not advised for real gameplay."
author = "Sean Wheeldon"
icon = "/mods/Pulchritudinousity/canon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }
