--ISO_639-1_code=PL
--Translated by: Google
CityscapesSpawn_LOB="Widoki miejskie: odtwarzacz Sloty"
CityscapesSpawn_LOB_D="Określa, które lokalizacje gracz odradzania miasta mogą tarło w."
CityscapesSpawn_LOB_EmptySpots="Puste gniazda"
CityscapesSpawn_LOB_EmptySpotsD="Miasta mogą pojawiać się w pustych miejscach gracz tarła."
CityscapesSpawn_LOB_AllSlots="Wszystkie gniazda"
CityscapesSpawn_LOB_AllSlotsD="Miasta mogą pojawiać się w dowolnym miejscu gracz odradzania."
CityscapesSpawn_LOB_OccupiedSlots="zajętych szczelin"
CityscapesSpawn_LOB_OccupiedSlotsD="Miasta mogą pojawiać wokół graczy."
CityscapesSpawn_LOB_false="Nie Sloty"
CityscapesSpawn_LOB_falseD="Miasta nie będzie tarło w miejscu gracz odradzania."

CityscapesTeam_LOB="Widoki miejskie: Gracz Slot zespołu"
CityscapesTeam_LOB_D="Definiuje właściciela miast zrodził się w zajętych gniazd, jeśli takie istnieją."
CityscapesTeam_LOB_Civilian="Cywil"
CityscapesTeam_LOB_CivilianD="Miasta w zajętych szczelin są cywilną kontrolą."
CityscapesTeam_LOB_LocalArmy="lokalna Army"
CityscapesTeam_LOB_CivilianD="Miasta w zajętych gniazd są kontrolowane przez tę armię."

CityscapesExpansion_LOB="Strefy miejskie: Expansion"
CityscapesExpansion_LOB_D="Określa, czy w strefach miast tarło rozszerzeń markerów."
CityscapesExpansion_LOB_Enabled="włączone"
CityscapesExpansion_LOB_EnabledD="Cywilne miasta tarło na markery dylatacyjnych."
CityscapesExpansion_LOB_Disabled="Niepełnosprawny"
CityscapesExpansion_LOB_DisabledD="Brak miast tarło na markery dylatacyjnych."

CityscapesLargeExpansion_LOB="Widoki miejskie: Duże Strefy rozszerzeń"
CityscapesLargeExpansion_LOB_D="Określa, czy miast tarło w dowolnych dużych stref rozszerzeń markerów."
CityscapesLargeExpansion_LOB_Enabled="włączone"
CityscapesLargeExpansion_LOB_EnabledD="Cywilne miasta tarło w dużych markerów ekspansji."
CityscapesLargeExpansion_LOB_Disabled="Niepełnosprawny"
CityscapesLargeExpansion_LOB_DisabledD="Brak dużych miast na tarło markerów ekspansji."

CityscapesObjective_LOB="Widoki miejskie: Obiektywne Markery"
CityscapesObjective_LOB_D="Określa, czy miast tarło na jakiekolwiek obiektywne markery."
CityscapesObjective_LOB_Enabled="włączone"
CityscapesObjective_LOB_EnabledD="Cywilne miasta tarło na obiektywnych markerów."
CityscapesObjective_LOB_Disabled="Niepełnosprawny"
CityscapesObjective_LOB_DisabledD="Brak miast tarło na obiektywnych markerów."