--ISO_639-1_code=PL
--Translated by: Google
CityscapesSpawn_LOB="Pejzaż miejscy: Gloty gracza"
CityscapesSpawn_LOB_D="Określa, które odtwarzacze odradzają miasta, które można spawnować w."
CityscapesSpawn_LOB_EmptySpots="Puste szczeliny"
CityscapesSpawn_LOB_EmptySpotsD="Miasta mogą pojawiać się w lokalizacjach pustych graczy."
CityscapesSpawn_LOB_AllSlots="Wszystkie automaty"
CityscapesSpawn_LOB_AllSlotsD="Miasta mogą spawnować w dowolnym miejscu odradza lokalizację."
CityscapesSpawn_LOB_OccupiedSlots="Zajęte gniazda"
CityscapesSpawn_LOB_OccupiedSlotsD="Miasta mogą spawnować wokół graczy."
CityscapesSpawn_LOB_false="Brak slotów"
CityscapesSpawn_LOB_falseD="Miasta nie pojawią się na miejscu odradzania przez gracza."

CityscapesTeam_LOB="Pejzaż miejscy: zespół gniazdo gracza"
CityscapesTeam_LOB_D="Określa właściciel miast zrodzonych w okupowanych szczelinach, jeśli istnieją."
CityscapesTeam_LOB_Civilian="Cywil"
CityscapesTeam_LOB_CivilianD="Miasta w okupowanych szczelinach są kontrolowane cywilne."
CityscapesTeam_LOB_LocalArmy="Lokalna armia"
CityscapesTeam_LOB_CivilianD="Miasta w okupowanych szczelinach są kontrolowane przez tę armię."

CityscapesExpansion_LOB="Pejzaż miejscy: Strefy rozszerzeń"
CityscapesExpansion_LOB_D="Określa, czy miasta pojawiają się w markerach stref ekspansji."
CityscapesExpansion_LOB_Enabled="Włączony"
CityscapesExpansion_LOB_EnabledD="Cywilne miasta pojawiają się w markerach ekspansji."
CityscapesExpansion_LOB_Disabled="Wyłączone"
CityscapesExpansion_LOB_DisabledD="Żadne miasta pojawiają się w markerach ekspansji."

CityscapesLargeExpansion_LOB="Pejzaże miejskie: Duże strefy rozszerzeń"
CityscapesLargeExpansion_LOB_D="Określa, czy miasta pojawiają się w żadnych dużych markerów stref rozszerzających."
CityscapesLargeExpansion_LOB_Enabled="Włączony"
CityscapesLargeExpansion_LOB_EnabledD="Cywilne miasta pojawiają się na dużych markerach rozszerzających."
CityscapesLargeExpansion_LOB_Disabled="Wyłączone"
CityscapesLargeExpansion_LOB_DisabledD="Żadne miast na dużych markerach rozszerzających."

CityscapesObjective_LOB="Pejzaż miejscy: Obiektywne znaczniki"
CityscapesObjective_LOB_D="Określa, czy miasta pojawiają się na dowolnych obiektywnych markerach."
CityscapesObjective_LOB_Enabled="Włączony"
CityscapesObjective_LOB_EnabledD="Cywilne miasta pojawiają się na obiektywnych markerach."
CityscapesObjective_LOB_Disabled="Wyłączone"
CityscapesObjective_LOB_DisabledD="Żadne miasta pojawiają się w obiektywnych markerach."
