--ISO_639-1_code=DE
--Translated by: Google
CityscapesSpawn_LOB="Cityscapes: Spieler Slots"
CityscapesSpawn_LOB_D="Legt fest, welche Spieler Spawnpunkt Städte in laichen können."
CityscapesSpawn_LOB_EmptySpots="leere Steckplätze"
CityscapesSpawn_LOB_EmptySpotsD="Die Städte können in leeren Spieler Spawnpunkt laichen."
CityscapesSpawn_LOB_AllSlots="Alle Steckplätze"
CityscapesSpawn_LOB_AllSlotsD="Die Städte können in jedem Spieler laichen Lage laichen."
CityscapesSpawn_LOB_OccupiedSlots="besetzter Schlitze"
CityscapesSpawn_LOB_OccupiedSlotsD="Die Städte können Spieler spawnen um."
CityscapesSpawn_LOB_false="keine Slots"
CityscapesSpawn_LOB_falseD="Die Städte werden nicht an Spieler Laich Standort laichen."

CityscapesTeam_LOB="Cityscapes: Spieler Slot-Team"
CityscapesTeam_LOB_D="Definiert den Besitzer der Städte in besetzten Schlitzen hervorgebracht, wenn sie vorhanden sind."
CityscapesTeam_LOB_Civilian="Zivilist"
CityscapesTeam_LOB_CivilianD="Städte in den besetzten Slots sind zivile gesteuert."
CityscapesTeam_LOB_LocalArmy="lokale Armee"
CityscapesTeam_LOB_CivilianD="Städte in der besetzten Slots werden von dieser Armee kontrolliert."

CityscapesExpansion_LOB="Cityscapes: Expansion Zones"
CityscapesExpansion_LOB_D="Legt fest, ob Städte auf Expansionszonen Marker laichen."
CityscapesExpansion_LOB_Enabled="aktiviert"
CityscapesExpansion_LOB_EnabledD="Zivile Städte laichen bei Expansion Markern."
CityscapesExpansion_LOB_Disabled="Deaktiviert"
CityscapesExpansion_LOB_DisabledD="Keine Städte laichen bei Expansion Markern."

CityscapesLargeExpansion_LOB="Stadtbilder: Große Erweiterungszonen"
CityscapesLargeExpansion_LOB_D="Legt fest, ob Städte bei allen großen Expansionszonen Marker laichen."
CityscapesLargeExpansion_LOB_Enabled="aktiviert"
CityscapesLargeExpansion_LOB_EnabledD="Zivile Städte im Allgemeinen Expansion Marker laichen."
CityscapesLargeExpansion_LOB_Disabled="Deaktiviert"
CityscapesLargeExpansion_LOB_DisabledD="Keine Städte im Allgemeinen Expansion Marker laichen."

CityscapesObjective_LOB="Cityscapes: Objective Marker"
CityscapesObjective_LOB_D="Legt fest, ob Städte an beliebigen Ziel-Marker laichen."
CityscapesObjective_LOB_Enabled="aktiviert"
CityscapesObjective_LOB_EnabledD="Zivile Städte an objektiven Marker laichen."
CityscapesObjective_LOB_Disabled="Deaktiviert"
CityscapesObjective_LOB_DisabledD="Keine Städte an objektiven Marker laichen."