--ISO_639-1_code=DE
--Translated by: Binary
CityscapesSpawn_LOB="Cityscapes: Spielerplätze"
CityscapesSpawn_LOB_D="Legt fest, an welchen Spieler Spawnpunkten Städte entstehen können"
CityscapesSpawn_LOB_EmptySpots="Leere Slots"
CityscapesSpawn_LOB_EmptySpotsD="Städte können an leeren Spielerstandorten spawnen."
CityscapesSpawn_LOB_AllSlots="Alle Slots"
CityscapesSpawn_LOB_AllSlotsD="Städte können an jedem Spielerstandort spawnen."
CityscapesSpawn_LOB_OccupiedSlots="Besetzte Slots"
CityscapesSpawn_LOB_OccupiedSlotsD="Städte können um die Spieler herum spawnen."
CityscapesSpawn_LOB_false="Keine Slots"
CityscapesSpawn_LOB_falseD="Städte spawnen nicht an Spielerstandorten."

CityscapesTeam_LOB="Cityscapes: Spieler-Slot-Team"
CityscapesTeam_LOB_D="Definiert den Besitz von Städten, die in besetzten Slots spawnen, falls sie existieren."
CityscapesTeam_LOB_Civilian="Zivilisten"
CityscapesTeam_LOB_CivilianD="Städte in besetzten Slots sind von Zivilisten kontrolliert."
CityscapesTeam_LOB_LocalArmy="Lokale Armee"
CityscapesTeam_LOB_CivilianD="Städte in besetzten Slots werden von dieser Armee kontrolliert."

CityscapesExpansion_LOB="Cityscapes: Erweiterungszonen"
CityscapesExpansion_LOB_D="Festlegung, ob Städte an den Erweiterungszonen-Markern spawnen können."
CityscapesExpansion_LOB_Enabled="Aktiviert"
CityscapesExpansion_LOB_EnabledD="Zivilistenstädte spawnen an den Erweiterungsmarkierungen."
CityscapesExpansion_LOB_Disabled="Deaktiviert"
CityscapesExpansion_LOB_DisabledD="Städte spawnen nicht an den Erweiterungsmarkierungen."

CityscapesLargeExpansion_LOB="Cityscapes: Große Expansionszonen"
CityscapesLargeExpansion_LOB_D="Bestimmt, ob Städte an allen großen Expansionszonenmarkierungen spawnen können."
CityscapesLargeExpansion_LOB_Enabled="Aktiviert"
CityscapesLargeExpansion_LOB_EnabledD="Ziviler Städte spawnen an großen Expansionsmarkierungen."
CityscapesLargeExpansion_LOB_Disabled="Deaktiviert"
CityscapesLargeExpansion_LOB_DisabledD="Städte spawnen nicht an grossen Expansionsmarkierungen."

CityscapesObjective_LOB="Cityscapes: Objektive Marker"
CityscapesObjective_LOB_D="Bestimmt, ob Städte an allen Zielmarken spawnen."
CityscapesObjective_LOB_Enabled="Aktiviert"
CityscapesObjective_LOB_EnabledD="Zivilistenstädte spawnen an den Zielmarkierungen."
CityscapesObjective_LOB_Disabled="Deaktiviert"
CityscapesObjective_LOB_DisabledD="Zivilstädte spawnen nicht an den Zielmarkierungen."
