name = "Waterlag"
uid = "25D57D85-9JA7-D842-GKG4-ASJDKG49G8S50"
version = 0.5
copyright = "© 2009–2018 Sean Wheeldon"
description = "Adds aquatic abilities to each building that isn't a factory, wall, silo, or experimental."
author = "Sean 'Balthazar' Wheeldon"
icon = "/mods/BrewLAN_Gameplay/Waterlag/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = {
}before = { }
after = { }
