name = "Stolen Tech"
uid = "16678e1e-7fc9-11e5-8bcf-STOLENTECH00"
version = 0
copyright = "© Various"
description = "Modifies the ALT-F2 cheatspawn menu, inspired by the FAF variant of it, for use with FA and the original Supreme Commander."
author = "Balthazar"
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
