--ISO_639-1_code=ZH
--Translated by: Google
seb2101_name="DMX防暴枪"
seb2101_desc="轻点防御"
Unit_Description_TeaD_001="光高效防御炮塔。配备了防暴枪。"

seb3101_name="SA0  -  100"
seb3101_desc="光雷达系统"
Unit_Description_TeaD_002="光雷达塔。能否透露隐形单位的位置。"

Unit_Description_TeaD_003="构建移动设备。"

tec0001_desc="车"
tec0002_desc="卡车"
tec0003_desc="公共汽车"
tec0004_desc="开创者"
tec0005_desc="盾"
tec0006_desc="自行车"
tec0007_desc="海洋之盾"
tec0008_desc="隐形车"
tec0009_desc="空童军"
tec0010_desc="救护车"
tec0011_desc="大飞机"
tec0012_desc="屏蔽飞机"
tec0101_desc="加特林老板"
tec0102_desc="坦克老板"
tec0103_desc="屏蔽老板博特"
tec0104_desc="大老板博特"

tead_waiting_for_no_rush="等待没有急于结束"
tead_pathfinder_wave="探路者波"
tead_wave1="浪潮集团1"
tead_DTwave1="损伤试验第1波"
tead_wave2="浪潮集团2"
tead_warn_cloak="警告：隐形部队入境"
tead_DTwave2="损害测试第2波"
tead_warn_fliers="警告：传单入境"
tead_wave3="浪潮集团3"
tead_boss1="老大1波"
tead_wave4="浪潮集团4"
tead_boss_final="最终Boss"

--TEAD大堂EN-US字符串
TeaD_Endless_LOB="TEAD：无尽模式"
TeaD_Endless_LOB_D="虽然启用波将循环与爱好者。"
TeaD_Endless_LOB_false="残"
TeaD_Endless_LOB_falseD="最终boss后游戏结束波作为正常的。"
TeaD_Endless_LOB_true="启用"
TeaD_Endless_LOB_trueD="游戏循环直到玩家死亡。"
TeaD_LOB_Endless_T="TEAD无尽的波浪模式。"
TeaD_LOB_Endless_D="虽然启用浪将循环，增量爱好者应用于每个复位。"
TeaD_LOB_Endless_falseT="无尽的浪禁用。"
TeaD_LOB_Endless_falseD="最后一波后游戏结束被击败。"
TeaD_LOB_Endless_trueT="无尽的浪启用。"
TeaD_LOB_Endless_trueD="胜利是不可能的。游戏运行，直到你最终被击败。"