--ISO_639-1_code=ZH
--Translated by: YuchenJimmy
seb2101_name="DMX鎮暴槍"
seb2101_desc="輕型點防禦"
Unit_Description_TeaD_001="輕型點防禦。配備了兩挺鎮暴槍。"

seb3101_name="SA0  -  100"
seb3101_desc="輕型雷達系統"
Unit_Description_TeaD_002="輕型雷達系統。能使防禦設施發現並攻擊匿蹤的單位。"

Unit_Description_TeaD_003="建造地面單位。"

tec0001_desc="汽車"
tec0002_desc="卡車"
tec0003_desc="公車"
tec0004_desc="開創者"
tec0005_desc="護盾"
tec0006_desc="自行車"
tec0007_desc="護盾陸戰隊"
tec0008_desc="隱形車"
tec0009_desc="空中偵察兵"
tec0010_desc="救護車"
tec0011_desc="戰機"
tec0012_desc="護盾戰機"
tec0101_desc="格林機械王"
tec0102_desc="坦克王"
tec0103_desc="護盾機械王"
tec0104_desc="巨大機械王"

tead_waiting_for_no_rush="本回合無敵軍來襲"
tead_pathfinder_wave="偵查兵"
tead_wave1="第一波敵軍來襲"
tead_DTwave1="第一波傷害測試"
tead_wave2="第二波敵軍來襲"
tead_warn_cloak="警告：匿蹤部隊入侵"
tead_DTwave2="第二波傷害測試"
tead_warn_fliers="警告：空軍來襲"
tead_wave3="第三波敵軍來襲"
tead_boss1="第一波魔王來襲"
tead_wave4="第四波敵軍來襲"
tead_boss_final="最终Boss來襲"

--Translated by: YuchenJimmy
TeaD_Endless_LOB="TEAD: 無盡模式"
TeaD_Endless_LOB_D="當開啟循環模式時為敵軍添加增益"
TeaD_Endless_LOB_false="關閉"
TeaD_Endless_LOB_falseD="與一般遊戲時相同，當您擊敗魔王後遊戲將會結束"
TeaD_Endless_LOB_true="啟用"
TeaD_Endless_LOB_trueD="重複進攻直到玩家陣亡"
TeaD_LOB_Endless_T="Tead: 啟用無盡模式"
TeaD_LOB_Endless_D="當啟用循環模式後，每波進攻重置時將會為敵軍添加增益"
TeaD_LOB_Endless_falseT="關閉無盡模式"
TeaD_LOB_Endless_falseD="遊戲將在最後一波敵人被擊敗後結束"
TeaD_LOB_Endless_trueT="啟用無盡模式"
TeaD_LOB_Endless_trueD="你是不可能獲勝的，遊戲將會持續到你被打敗為止。"
