name = "Baristas"
uid = "25D57D85-9JA7-D842-GKG4-ORIGIN0000001"
version = 1
copyright = "© 2017–2018 Sean Wheeldon"
description = "Lists each unit's source mod as one of its abilities."
author = "Balthazar"
icon = "/mods/BrewLAN_Plenae/UnitOrigin/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = {
}before = { }
after = { }
