--ISO_639-1_code=CS
--Translated by: Google
CityscapesSpawn_LOB="Pohledy: Player Slots"
CityscapesSpawn_LOB_D="Definuje, které hráč potěr umístění města mohou plodit u."
CityscapesSpawn_LOB_EmptySpots="prázdné sloty"
CityscapesSpawn_LOB_EmptySpotsD="Města mohou plodit v prázdných místech hráč třít."
CityscapesSpawn_LOB_AllSlots="Všechny sloty"
CityscapesSpawn_LOB_AllSlotsD="Města mohou plodit v libovolném místě hráč třít."
CityscapesSpawn_LOB_OccupiedSlots="obsazené sloty"
CityscapesSpawn_LOB_OccupiedSlotsD="Města mohou plodit kolem hráče."
CityscapesSpawn_LOB_false="No Slots"
CityscapesSpawn_LOB_falseD="Města nebude plodit na místě hráčem třít."

CityscapesTeam_LOB="Pohledy: Player Slot Team"
CityscapesTeam_LOB_D="Definuje vlastníka měst plodil v obsazených slotů, pokud existují."
CityscapesTeam_LOB_Civilian="Civilní"
CityscapesTeam_LOB_CivilianD="Města v obsazených slotů jsou civilní pod kontrolou."
CityscapesTeam_LOB_LocalArmy="místní armáda"
CityscapesTeam_LOB_CivilianD="Města v obsazených slotů jsou řízeny této armády."

CityscapesExpansion_LOB="Pohledy: Dilatační zóny"
CityscapesExpansion_LOB_D="Určuje, zda měst třou v expanzních zón markerů."
CityscapesExpansion_LOB_Enabled="povoleno"
CityscapesExpansion_LOB_EnabledD="Civilní města třou na expanzní markerů."
CityscapesExpansion_LOB_Disabled="invalidní"
CityscapesExpansion_LOB_DisabledD="Žádná města třou v expanzních markerů."

CityscapesLargeExpansion_LOB="Pohledy: velkou expanzi Zones"
CityscapesLargeExpansion_LOB_D="Určuje, zda města třou na jakékoliv velké dilatační zóny markerů."
CityscapesLargeExpansion_LOB_Enabled="povoleno"
CityscapesLargeExpansion_LOB_EnabledD="Civilní města třou ve velkých dilatačních markerů."
CityscapesLargeExpansion_LOB_Disabled="invalidní"
CityscapesLargeExpansion_LOB_DisabledD="Žádná města třou ve velkých dilatačních markerů."

CityscapesObjective_LOB="Pohledy: Cíl Markers"
CityscapesObjective_LOB_D="Určuje, zda měst třou na nějakou objektivní markery."
CityscapesObjective_LOB_Enabled="povoleno"
CityscapesObjective_LOB_EnabledD="Civilní města třou na objektivních ukazatelů."
CityscapesObjective_LOB_Disabled="invalidní"
CityscapesObjective_LOB_DisabledD="Žádná města třou na objektivních ukazatelů."