--ISO_639-1_code=CS
--Translated by: Google
CityscapesSpawn_LOB="Městské scenérie: Hráč sloty"
CityscapesSpawn_LOB_D="Definuje, který hráč Spawn Místní města mohou rozbíhat."
CityscapesSpawn_LOB_EmptySpots="Prázdné sloty"
CityscapesSpawn_LOB_EmptySpotsD="Města mohou potěšit v prázdném hráči spawn místech."
CityscapesSpawn_LOB_AllSlots="Všechny sloty"
CityscapesSpawn_LOB_AllSlotsD="Města mohou spawn v libovolném hráči."
CityscapesSpawn_LOB_OccupiedSlots="Obsazené sloty"
CityscapesSpawn_LOB_OccupiedSlotsD="Města mohou potěšit kolem hráčů."
CityscapesSpawn_LOB_false="Žádné sloty"
CityscapesSpawn_LOB_falseD="Města nebudou spawn na hráče Chowwn Location."

CityscapesTeam_LOB="Městské scenérie: Hráč slot Team"
CityscapesTeam_LOB_D="Definuje majitele měst plodených v obsazených slotech, pokud existují."
CityscapesTeam_LOB_Civilian="Civilní"
CityscapesTeam_LOB_CivilianD="Města v obsazených slotech jsou civilní."
CityscapesTeam_LOB_LocalArmy="Místní armáda"
CityscapesTeam_LOB_CivilianD="Města v obsazených slotech jsou řízena touto armádou."

CityscapesExpansion_LOB="Městské scenérie: expanzní zóny"
CityscapesExpansion_LOB_D="Určuje, zda města spawn na markerech expanzních zón."
CityscapesExpansion_LOB_Enabled="Povolený"
CityscapesExpansion_LOB_EnabledD="Civilní města spawn v expanzních značkách."
CityscapesExpansion_LOB_Disabled="Postižený"
CityscapesExpansion_LOB_DisabledD="Žádná města se rozbíjejí v expanzních značkách."

CityscapesLargeExpansion_LOB="Městské scenérie: Velké expanzní zóny"
CityscapesLargeExpansion_LOB_D="Určuje, zda města spawn v jakýchkoli velkých markerech expanzních zón."
CityscapesLargeExpansion_LOB_Enabled="Povolený"
CityscapesLargeExpansion_LOB_EnabledD="Civilní města se rozbije ve velkých expanzních značkách."
CityscapesLargeExpansion_LOB_Disabled="Postižený"
CityscapesLargeExpansion_LOB_DisabledD="Žádná města se rozběhne ve velkých expanzních značkách."

CityscapesObjective_LOB="Městské scenérie: Objektivní značky"
CityscapesObjective_LOB_D="Určuje, zda města se objeví na všech objektivních značkách."
CityscapesObjective_LOB_Enabled="Povolený"
CityscapesObjective_LOB_EnabledD="Civilní města spawn na objektivních značkách."
CityscapesObjective_LOB_Disabled="Postižený"
CityscapesObjective_LOB_DisabledD="Žádná města se objeví na objektivních značkách."
