--ISO_639-1_code=PL
--Translated by: Google
seb2101_name="DMX Riot Gun."
seb2101_desc="Defense Light Point."
Unit_Description_TeaD_001="Lekka sprawna wieżyczka obronna. Wyposażony w broń zamieszek."

seb3101_name="SA0 - 100."
seb3101_desc="Lekki system radarowy"
Unit_Description_TeaD_002="Lekka wieża radarowa. Może ujawnić lokalizacje niewidzialnych jednostek."

Unit_Description_TeaD_003="Konstruuje jednostki mobilne."

tec0001_desc="Samochód"
tec0002_desc="Samochód ciężarowy"
tec0003_desc="Autobus"
tec0004_desc="Pionier"
tec0005_desc="Tarcza"
tec0006_desc="Rower"
tec0007_desc="Tarcza morska"
tec0008_desc="Car gołączony"
tec0009_desc="Skaut"
tec0010_desc="Ambulans"
tec0011_desc="Duży samolot"
tec0012_desc="Ekranowany samolot"
tec0101_desc="Gatling Boss."
tec0102_desc="Tank Boss."
tec0103_desc="Ekranowany boss Bot."
tec0104_desc="Big Boss Bot."

tead_waiting_for_no_rush="Czekam na koniec No-Rush"
tead_pathfinder_wave="Fala Pathfinder."
tead_wave1="Wave Group 1."
tead_DTwave1="Fala testowa uszkodzenia 1"
tead_wave2="Grupa falowa 2."
tead_warn_cloak="OSTRZEŻENIE: Jednostki zamaskowe przychodzące"
tead_DTwave2="Fala testowa uszkodzenia 2"
tead_warn_fliers="OSTRZEŻENIE: Fliers Inbound"
tead_wave3="Wave Group 3."
tead_boss1="Boss fala 1."
tead_wave4="Wave Group 4."
tead_boss_final="Główny przeciwnik"

--Lobby TEAD Hol En-US Struns
TeaD_Endless_LOB="TEAD: niekończący się tryb"
TeaD_Endless_LOB_D="Podczas gdy fale włączone będą pętlą z buffami."
TeaD_Endless_LOB_false="Wyłączone"
TeaD_Endless_LOB_falseD="Gra kończy się po ostatecznym fali bossów jako normalnie."
TeaD_Endless_LOB_true="Włączony"
TeaD_Endless_LOB_trueD="Pętle do gry, aż gracze umrą."
TeaD_LOB_Endless_T="Tryb niekończących się fal związanych z niekończącymi się."
TeaD_LOB_Endless_D="Podczas gdy fale włączone będą pętli, z przyrostowymi buffami zastosowanymi z każdym resetem."
TeaD_LOB_Endless_falseT="Niekończące się fale wyłączone."
TeaD_LOB_Endless_falseD="Gra kończy się po pokonaniu ostatniej fali."
TeaD_LOB_Endless_trueT="Niekończące się fale włączone."
TeaD_LOB_Endless_trueD="Zwycięstwo jest niemożliwe. Gra biegnie, dopóki nie zostaniesz ostatecznie pokonany."
