--ISO_639-1_code=PL
--Translated by: Google
seb2101_name="DMX Riot Gun"
seb2101_desc="Punkt świetlny obrony"
Unit_Description_TeaD_001="Światło wydajny wieżyczka obronna. Wyposażony w pistolet zamieszek."

seb3101_name="SA0 - 100"
seb3101_desc="Lekki system radarowy"
Unit_Description_TeaD_002="Światło wieży radarowej. Może ujawnić lokalizacje jednostek niewidzialnych."

Unit_Description_TeaD_003="Konstruuje jednostek mobilnych."

tec0001_desc="Samochód"
tec0002_desc="Samochód ciężarowy"
tec0003_desc="Autobus"
tec0004_desc="Pionier"
tec0005_desc="Tarcza"
tec0006_desc="Rower"
tec0007_desc="Tarcza Marine"
tec0008_desc="maskowana samochodów"
tec0009_desc="Air Scout"
tec0010_desc="Karetka pogotowia"
tec0011_desc="duży Samolot"
tec0012_desc="Samoloty ekranowany"
tec0101_desc="Gatling Boss"
tec0102_desc="zbiornik Boss"
tec0103_desc="Ekranowane Boss Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Oczekiwanie na no-pędu do końca"
tead_pathfinder_wave="Pathfinder fala"
tead_wave1="grupa fala 1"
tead_DTwave1="Uszkodzenie fali Test 1"
tead_wave2="grupa Wave 2"
tead_warn_cloak="Ostrzeżenie: maskowana jednostki przychodzących"
tead_DTwave2="Uszkodzenie fali Test 2"
tead_warn_fliers="Warning: Fliers przychodzące"
tead_wave3="grupa Wave 3"
tead_boss1="Boss fali 1"
tead_wave4="grupa Wave 4"
tead_boss_final="Główny przeciwnik"

--struny TeaD Lobby EN-US
TeaD_Endless_LOB="TeaD: Tryb Kompletne"
TeaD_Endless_LOB_D="Podczas gdy włączone fale będzie pętla z buffy."
TeaD_Endless_LOB_false="Niepełnosprawny"
TeaD_Endless_LOB_falseD="Końce gry po końcowym występu fali normalnie."
TeaD_Endless_LOB_true="włączone"
TeaD_Endless_LOB_trueD="Gra pętle aż gracze umrzeć."
TeaD_LOB_Endless_T="TeaD fale niekończące tryb."
TeaD_LOB_Endless_D="Podczas gdy pętla włączona fale wola, z przyrostowych buffy stosowana z każdym resecie."
TeaD_LOB_Endless_falseT="niekończące się fale wyłączona."
TeaD_LOB_Endless_falseD="Końce gry po ostatniej fali jest pokonany."
TeaD_LOB_Endless_trueT="niekończące się fale włączony."
TeaD_LOB_Endless_trueD="Zwycięstwo jest niemożliwe. Gra działa, dopóki nie są ostatecznie pokonany."