name = "BrewLAN: Gantry AIx 3"
uid = "25D57D85-7D84-27HT-A503-BR3WGA0000001"
version = 0.1
copyright = "© 2015 Sean Wheeldon"
description = "AIx Gantry superhax. Mass-gated exponential growth, with discounts instead of free resources. Works for Aeon & UEF."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_Modules/BrewGantry1/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
