--ISO_639-1_code=ES
--Translated by: Google
CityscapesSpawn_LOB="Paisajes urbanos: Slots de jugador"
CityscapesSpawn_LOB_D="Define a qué jugadores aparecen las ubicaciones las ciudades pueden engendrarlas."
CityscapesSpawn_LOB_EmptySpots="Tragamonedas vacias"
CityscapesSpawn_LOB_EmptySpotsD="Las ciudades pueden generarse en lugares de engendrado de jugadores vacíos."
CityscapesSpawn_LOB_AllSlots="Todas las ranuras"
CityscapesSpawn_LOB_AllSlotsD="Las ciudades pueden generar lugar en cualquier lugar de engendro."
CityscapesSpawn_LOB_OccupiedSlots="Ranuras ocupadas"
CityscapesSpawn_LOB_OccupiedSlotsD="Las ciudades pueden generar jugadores."
CityscapesSpawn_LOB_false="No hay ranuras"
CityscapesSpawn_LOB_falseD="Las ciudades no se engendrarán en la ubicación del engendro de jugadores."

CityscapesTeam_LOB="Paisajes urbanos: Equipo de tragamonedas del jugador"
CityscapesTeam_LOB_D="Define el propietario de las ciudades generadas en tragamonedas ocupadas, si existen."
CityscapesTeam_LOB_Civilian="Civil"
CityscapesTeam_LOB_CivilianD="Las ciudades en tragamonedas ocupadas son controladas civiles."
CityscapesTeam_LOB_LocalArmy="Ejército local"
CityscapesTeam_LOB_CivilianD="Las ciudades en tragamonedas ocupadas son controladas por ese ejército."

CityscapesExpansion_LOB="Paisajes urbanos: Zonas de expansión."
CityscapesExpansion_LOB_D="Determina si las ciudades engendran en los marcadores de las zonas de expansión."
CityscapesExpansion_LOB_Enabled="Activado"
CityscapesExpansion_LOB_EnabledD="Ciudades civiles engendran en marcadores de expansión."
CityscapesExpansion_LOB_Disabled="Discapacitado"
CityscapesExpansion_LOB_DisabledD="No hay ciudades engendradas en marcadores de expansión."

CityscapesLargeExpansion_LOB="Paisajes urbanos: grandes zonas de expansión"
CityscapesLargeExpansion_LOB_D="Determina si las ciudades engendran en cualquier grupo de zonas de expansión grandes."
CityscapesLargeExpansion_LOB_Enabled="Activado"
CityscapesLargeExpansion_LOB_EnabledD="Ciudades civiles engendran en grandes marcadores de expansión."
CityscapesLargeExpansion_LOB_Disabled="Discapacitado"
CityscapesLargeExpansion_LOB_DisabledD="Ninguna ciudades engendran en grandes marcadores de expansión."

CityscapesObjective_LOB="Paisajes urbanos: marcadores objetivos."
CityscapesObjective_LOB_D="Determina si las ciudades engendran en cualquier marcador objetivo."
CityscapesObjective_LOB_Enabled="Activado"
CityscapesObjective_LOB_EnabledD="Ciudades civiles engendran en marcadores objetivos."
CityscapesObjective_LOB_Disabled="Discapacitado"
CityscapesObjective_LOB_DisabledD="No hay ciudades engendradas en marcadores objetivos."
