--ISO_639-1_code=ES
--Translated by: Google
CityscapesSpawn_LOB="Paisajes urbanos: jugador de tragamonedas"
CityscapesSpawn_LOB_D="Define qué localizaciones jugador desovar las ciudades pueden desovar al."
CityscapesSpawn_LOB_EmptySpots="Las ranuras vacías"
CityscapesSpawn_LOB_EmptySpotsD="Las ciudades pueden desovar en lugares vacíos jugador desovar."
CityscapesSpawn_LOB_AllSlots="todas las ranuras"
CityscapesSpawn_LOB_AllSlotsD="Las ciudades pueden generar en cualquier lugar reproductor de desove."
CityscapesSpawn_LOB_OccupiedSlots="slots ocupados"
CityscapesSpawn_LOB_OccupiedSlotsD="Las ciudades pueden generar alrededor de los jugadores."
CityscapesSpawn_LOB_false="No hay ranuras"
CityscapesSpawn_LOB_falseD="Las ciudades no se generan en la ubicación jugador desovar."

CityscapesTeam_LOB="Team Slot jugador: paisajes urbanos"
CityscapesTeam_LOB_D="Define el dueño de ciudades generados en las ranuras ocupadas, si es que existen."
CityscapesTeam_LOB_Civilian="Civil"
CityscapesTeam_LOB_CivilianD="Ciudades en las ranuras ocupadas son controlados civil."
CityscapesTeam_LOB_LocalArmy="Ejército local"
CityscapesTeam_LOB_CivilianD="Ciudades en las ranuras ocupadas son controladas por ese ejército."

CityscapesExpansion_LOB="Urbanos: Zonas de expansión"
CityscapesExpansion_LOB_D="Determina si las ciudades desovan en marcadores zonas de expansión."
CityscapesExpansion_LOB_Enabled="Activado"
CityscapesExpansion_LOB_EnabledD="ciudades civiles desovan en los marcadores de expansión."
CityscapesExpansion_LOB_Disabled="Discapacitado"
CityscapesExpansion_LOB_DisabledD="No hay ciudades desovan en los marcadores de expansión."

CityscapesLargeExpansion_LOB="Cityscapes: Zonas de expansión a gran"
CityscapesLargeExpansion_LOB_D="Determina si las ciudades desovan en cualquier marcadores grandes zonas de expansión."
CityscapesLargeExpansion_LOB_Enabled="Activado"
CityscapesLargeExpansion_LOB_EnabledD="ciudades civiles desovan en grandes marcadores de expansión."
CityscapesLargeExpansion_LOB_Disabled="Discapacitado"
CityscapesLargeExpansion_LOB_DisabledD="No hay ciudades desovan en grandes marcadores de expansión."

CityscapesObjective_LOB="Paisajes urbanos: marcadores objetivos"
CityscapesObjective_LOB_D="Determina si las ciudades desovan en cualquier marcadores objetivos."
CityscapesObjective_LOB_Enabled="Activado"
CityscapesObjective_LOB_EnabledD="ciudades civiles desovan en marcadores objetivos."
CityscapesObjective_LOB_Disabled="Discapacitado"
CityscapesObjective_LOB_DisabledD="No hay ciudades desovan en marcadores objetivos."