name = "Research & Daiquiris"
uid = "25D57D85-9JA7-D842-BREW-RESEARCH00000"
version = 0.0
copyright = "© 2018 Sean Wheeldon"
description = "Adds research buildings that unlock new units."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_Units/BrewResearch/R&D.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
