name = "BrewLAN: Research & Daiquiris"
uid = "25D57D85-9JA7-D842-BREW-RESEARCH00006"
version = 0.6
copyright = "© 2018 Sean Wheeldon"
description = "Separates the hardware and software for tech levels, and adds research for unlocking tech tevels and units."
author = "Balthazar"
icon = "/mods/BrewLAN_Units/BrewResearch/R&D.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }
