name = "BrewLAN: Modules"
uid = "190261d0-4bb0-11e2-bcSC-BLMODULES001"
version = 1
copyright = "© 2009–2018 Sean Wheeldon"
description = "Container for the BrewLAN modules for AI, AI cheats, UI, and Gantry changes."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_Modules/folder.png"
selectable = false
enabled = false
exclusive = false
ui_only = false
