name = "Crate Drop"
uid = "BREWLANS-a0a7-426d-88f2-CRATESZ00009"
version = 0.9
copyright = "© 2015—2016 Sean Wheeldon"
description = "Random crate drops happen across the land. Will they be good? Will they be bad? Who knows."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_RNG/cratedrop/lewt.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = {
}before = { }
after = { }
