--ISO_639-1_code=CS
--Translated by: Google
seb2101_name="DMX Riot Gun"
seb2101_desc="Light Point Defense"
Unit_Description_TeaD_001="Light účinný obranný revolver. Vybavena brokovnici."

seb3101_name="SA0 - 100"
seb3101_desc="Light Radar System"
Unit_Description_TeaD_002="Light radar věž. Může odhalit umístění neviditelných jednotek."

Unit_Description_TeaD_003="Buduje mobilní jednotky."

tec0001_desc="Auto"
tec0002_desc="nákladní auto"
tec0003_desc="Autobus"
tec0004_desc="Průkopník"
tec0005_desc="Štít"
tec0006_desc="Kolo"
tec0007_desc="Shield Marine"
tec0008_desc="zahalená do auta"
tec0009_desc="Air Scout"
tec0010_desc="záchranná služba"
tec0011_desc="Big letadla"
tec0012_desc="stíněný Aircraft"
tec0101_desc="Gatling Boss"
tec0102_desc="Tank Boss"
tec0103_desc="Stíněný Boss Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Čekání na no-spěch na konec"
tead_pathfinder_wave="Pathfinder wave"
tead_wave1="skupina vlna 1"
tead_DTwave1="Poškození testovací vlna 1"
tead_wave2="skupina Wave 2"
tead_warn_cloak="Varovné: neviditelnou jednotku příchozí"
tead_DTwave2="Poškození Test vlna 2"
tead_warn_fliers="Varování: letáky příchozí"
tead_wave3="Wave skupina 3"
tead_boss1="Boss vlna 1"
tead_wave4="skupina Wave 4"
tead_boss_final="Final Boss"