--ISO_639-1_code=CS
--Translated by: Oaks
seb2101_name="DMX Dělo Vzpoura"
seb2101_desc="Lehká obranná věž."
Unit_Description_TeaD_001="Lehká obranná věž, vybavena dělem Vzpoura."

seb3101_name="SA0 - 100"
seb3101_desc="Lehký radar"
Unit_Description_TeaD_002="Lehká radarová věž. Odhaluje maskované jednotky."

Unit_Description_TeaD_003="Staví mobilní jednotky."

tec0001_desc="Auto"
tec0002_desc="Nákladní auto"
tec0003_desc="Autobus"
tec0004_desc="Průkopník"
tec0005_desc="Štít"
tec0006_desc="Kolo"
tec0007_desc="Mariňák se štítem"
tec0008_desc="Maskované auto"
tec0009_desc="Letecký Průzkumník"
tec0010_desc="Záchranná služba"
tec0011_desc="Velké letadlo"
tec0012_desc="Maskované letadlo"
tec0101_desc="Gatling Boss"
tec0102_desc="Tank Boss"
tec0103_desc="Boss bot se štítem"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Čekání na konec bez spěchu"
tead_pathfinder_wave="Naváděči"
tead_wave1="1. vlna"
tead_DTwave1="1. vlna test poškození"
tead_wave2="2. vlna"
tead_warn_cloak="Varování: Maskované jednotky na cestě"
tead_DTwave2="2. vlna test poškození"
tead_warn_fliers="Varování: Letecké jednotky na cestě"
tead_wave3="3. vlna"
tead_boss1="Boss"
tead_wave4="4. vlna"
tead_boss_final="Finální Boss"