name = "BrewLAN: RNG mods"
uid = "190261d0-4bb0-11e2-bcSC-BLRNGMODSS02"
version = 2
copyright = "© 2009–2022 Sean Wheeldon"
description = "Container for the BrewLAN extra unit sub-mods; Cost Variance, Crate Drop, Lucky Dip, and others."
author = "Balthazar"
icon = "/mods/BrewLAN_RNG/folder.png"
selectable = false
enabled = false
exclusive = false
ui_only = false
