--ISO_639-1_code=ES
--Translated by: Google
seb2101_name="DMX Gun"
seb2101_desc="Punto de luz defensa"
Unit_Description_TeaD_001="Torreta defensiva de eficiencia ligera. Equipado con una pistola antidisturbios."

seb3101_name="SA0 - 100"
seb3101_desc="Sistema de radar ligero"
Unit_Description_TeaD_002="Torre de radar ligero. Puede revelar las ubicaciones de las unidades invisibles."

Unit_Description_TeaD_003="Construye unidades móviles."

tec0001_desc="Coche"
tec0002_desc="Camión"
tec0003_desc="Autobús"
tec0004_desc="Pionero"
tec0005_desc="Blindaje"
tec0006_desc="Bicicleta"
tec0007_desc="Escudo marino"
tec0008_desc="Coche encapuchado"
tec0009_desc="Scout"
tec0010_desc="Ambulancia"
tec0011_desc="Aeronave grande"
tec0012_desc="Aviones blindados"
tec0101_desc="Jefe de Gatling"
tec0102_desc="Jefe de tanque"
tec0103_desc="Boss Blindle Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Esperando no al final."
tead_pathfinder_wave="Onda de pathfinder"
tead_wave1="Grupo de onda 1"
tead_DTwave1="Onda de prueba de daños 1"
tead_wave2="Grupo de onda 2"
tead_warn_cloak="ADVERTENCIA: Unidades encapuchadas entrantes"
tead_DTwave2="Daño de la onda de prueba 2"
tead_warn_fliers="Advertencia: volantes entrantes"
tead_wave3="Grupo de onda 3"
tead_boss1="BOSS WAVE 1"
tead_wave4="Grupo de onda 4"
tead_boss_final="Jefe final"

--TEAD LOBBY EN-STRINGS
TeaD_Endless_LOB="Tead: Modo sin fin"
TeaD_Endless_LOB_D="Si bien las olas habilitadas se bucle con los buffs."
TeaD_Endless_LOB_false="Discapacitado"
TeaD_Endless_LOB_falseD="El juego termina después de la onda de jefe final de forma normal."
TeaD_Endless_LOB_true="Activado"
TeaD_Endless_LOB_trueD="Bucles de juego hasta que los jugadores mueran."
TeaD_LOB_Endless_T="TEAD MODO DE OILLAS DE INDINCES DE TEAD."
TeaD_LOB_Endless_D="Si bien las ondas habilitadas se bucle, con aficionados incrementales aplicados con cada reinicio."
TeaD_LOB_Endless_falseT="Olas infinitas deshabilitadas."
TeaD_LOB_Endless_falseD="El juego termina después de que la última ola es derrotada."
TeaD_LOB_Endless_trueT="Ondas sin fin habilitadas."
TeaD_LOB_Endless_trueD="La victoria es imposible. El juego se ejecuta hasta que finalmente seas derrotado."
