--ISO_639-1_code=ES
--Translated by: Google
seb2101_name="DMX antidisturbios pistola"
seb2101_desc="Defensa Point Light"
Unit_Description_TeaD_001="torreta de defensa eficiente la luz. Equipado con un arma de alboroto."

seb3101_name="SA0 - 100"
seb3101_desc="Sistema de Radar luz"
Unit_Description_TeaD_002="torre de radar luz. Puede revelar la ubicación de las unidades invisibles."

Unit_Description_TeaD_003="Construye unidades móviles."

tec0001_desc="Coche"
tec0002_desc="Camión"
tec0003_desc="Autobús"
tec0004_desc="Pionero"
tec0005_desc="Proteger"
tec0006_desc="Bicicleta"
tec0007_desc="escudo de Marina"
tec0008_desc="coche envuelta"
tec0009_desc="explorador de aire"
tec0010_desc="Ambulancia"
tec0011_desc="grandes Aviones"
tec0012_desc="Aviones blindado"
tec0101_desc="Gatling jefe"
tec0102_desc="Boss del tanque"
tec0103_desc="Blindado jefe Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Esperando no compatibles con prisa por terminar"
tead_pathfinder_wave="ola Pathfinder"
tead_wave1="1 grupo de olas"
tead_DTwave1="de onda de prueba de daños 1"
tead_wave2="grupo de olas 2"
tead_warn_cloak="Advertencia: Cloaked unidades de entrada"
tead_DTwave2="ola prueba de daño 2"
tead_warn_fliers="Advertencia: Los volantes de entrada"
tead_wave3="grupo de ondas 3"
tead_boss1="onda de Boss 1"
tead_wave4="grupo de la onda 4"
tead_boss_final="Jefe final"