--ISO_639-1_code=ES
--Translated by: Google
seb2101_name="DMX antidisturbios pistola"
seb2101_desc="Defensa Point Light"
Unit_Description_TeaD_001="torreta de defensa eficiente la luz. Equipado con un arma de alboroto."

seb3101_name="SA0 - 100"
seb3101_desc="Sistema de Radar luz"
Unit_Description_TeaD_002="torre de radar luz. Puede revelar la ubicación de las unidades invisibles."

Unit_Description_TeaD_003="Construye unidades móviles."

tec0001_desc="Carro"
tec0002_desc="Camión"
tec0003_desc="Autobús"
tec0004_desc="Pionero"
tec0005_desc="Proteger"
tec0006_desc="Bicicleta"
tec0007_desc="escudo de Marina"
tec0008_desc="Cloaked coche"
tec0009_desc="explorador de aire"
tec0010_desc="Ambulancia"
tec0011_desc="grandes Aviones"
tec0012_desc="Aviones blindado"
tec0101_desc="Gatling jefe"
tec0102_desc="Boss del tanque"
tec0103_desc="Blindado jefe Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Esperando no compatibles con prisa para fines"
tead_pathfinder_wave="ola Pathfinder"
tead_wave1="1 grupo de olas"
tead_DTwave1="de onda de prueba de daños 1"
tead_wave2="grupo de olas 2"
tead_warn_cloak="Advertencia: Cloaked unidades entrantes"
tead_DTwave2="ola prueba de daño 2"
tead_warn_fliers="Advertencia: Los volantes de entrada"
tead_wave3="grupo de ondas 3"
tead_boss1="onda de Boss 1"
tead_wave4="grupo de la onda 4"
tead_boss_final="Jefe final"

--cuerdas Tead Vestíbulo EN-US
TeaD_Endless_LOB="Tead: modo sin fin"
TeaD_Endless_LOB_D="Mientras que las ondas habilitados se repetirá con los aficionados."
TeaD_Endless_LOB_false="Discapacitado"
TeaD_Endless_LOB_falseD="extremos juego después de jefe final Wave como normal."
TeaD_Endless_LOB_true="Activado"
TeaD_Endless_LOB_trueD="bucles de juego hasta que los jugadores mueren."
TeaD_LOB_Endless_T="Tead modo de ondas sin fin."
TeaD_LOB_Endless_D="Mientras las ondas de bucle habilitados voluntad, con los aficionados incrementales aplica con cada reinicio."
TeaD_LOB_Endless_falseT="olas interminables desactivados."
TeaD_LOB_Endless_falseD="juego termina después de la última ola es derrotado."
TeaD_LOB_Endless_trueT="olas interminables habilitadas."
TeaD_LOB_Endless_trueD="La victoria es imposible. Juego se ejecuta hasta que esté finalmente derrotado."