name = "BrewLAN: Penetration"
uid = "25D57D85-9JA7-D842-BREW-AIR00000000023"
version = 2.3
copyright = "© 2018–2022 Sean Wheeldon"
description = "Adds extended aircraft options."
author = "Balthazar"
icon = "/mods/BrewLAN_Units/BrewAir/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
