name = "Ultimate Superweapons"
uid = "16678e1e-7fc9-11e5-8bcf-Wonder000000"
version = 0.0
copyright = "© 2019 Sean Wheeldon"
description = "Adds AoE style wonders to the game that allow a timed victory once constructed. UI unfinished."
author = "Balthazar"
icon = "/mods/BrewLAN_Gameplay/SuperWonder/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
