name = "Antimineshootypillen"
uid = "1ad6c93a-d1cc-4974-91f0-bdd29e49d4ca"
version = 0
copyright = "© 2021 Sean Wheeldon"
description = "Makes mines untargetable."
author = "Balthazar"
--icon = "/mods/BrewLAN_Gameplay/antimass/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
