--ISO_639-1_code=RU
--Translated by: Ajay
CityscapesSpawn_LOB="Урбанизация: слоты игрока"
CityscapesSpawn_LOB_D="Определяет, на каких стартовых позициях игроков могут создаваться города."
CityscapesSpawn_LOB_EmptySpots="Пустые слоты"
CityscapesSpawn_LOB_EmptySpotsD="Города могут быть созданы на стартовых позициях, не занятых игроками."
CityscapesSpawn_LOB_AllSlots="Все слоты"
CityscapesSpawn_LOB_AllSlotsD="Города могут быть созданы на любых стартовых позициях."
CityscapesSpawn_LOB_OccupiedSlots="Занятые слоты"
CityscapesSpawn_LOB_OccupiedSlotsD="Города могут быть созданы вокруг игроков."
CityscapesSpawn_LOB_false="Без слотов"
CityscapesSpawn_LOB_falseD="Города не будут появляться на стартовых позициях игроков."

CityscapesTeam_LOB="Урбанизация: слоты игрока - команда"
CityscapesTeam_LOB_D="Определяет, под чьим контролем находятся города, созданные в занятых слотах, при наличии таковых."
CityscapesTeam_LOB_Civilian="Гражданские"
CityscapesTeam_LOB_CivilianD="Города в занятых слотах контроллируются гражданскими."
CityscapesTeam_LOB_LocalArmy="Местная армия"
CityscapesTeam_LOB_CivilianD="Города в занятых слотах контроллируются этой армией."

CityscapesExpansion_LOB="Урбанизация: зоны расширения"
CityscapesExpansion_LOB_D="Определяет создание городов в зонах расширения."
CityscapesExpansion_LOB_Enabled="Включено"
CityscapesExpansion_LOB_EnabledD="Города будут создаваться в зонах расширения."
CityscapesExpansion_LOB_Disabled="Выключено"
CityscapesExpansion_LOB_DisabledD="Города не будут создаваться в зонах расширения."

CityscapesLargeExpansion_LOB="Урбанизация: большие зоны расширения"
CityscapesLargeExpansion_LOB_D="Определяет создание городов в больших зонах расширения."
CityscapesLargeExpansion_LOB_Enabled="Включено"
CityscapesLargeExpansion_LOB_EnabledD="Города будут создаваться в больших зонах расширения."
CityscapesLargeExpansion_LOB_Disabled="Выключено"
CityscapesLargeExpansion_LOB_DisabledD="Города не будут создаваться в больших зонах расширения."

CityscapesObjective_LOB="Урбанизация: метки задания"
CityscapesObjective_LOB_D="Определяет создание городов на метках целей боевого задания."
CityscapesObjective_LOB_Enabled="Включено"
CityscapesObjective_LOB_EnabledD="Города будут создаваться на метках целей боевого задания."
CityscapesObjective_LOB_Disabled="Выключено"
CityscapesObjective_LOB_DisabledD="Города не будут создаваться на метках целей боевого задания."
