name = "Cityscapes: Cybran"
uid = "190261d0-4bb0-11e2-bcSC-CITIESC00001"
version = 0
copyright = "© 2020–2020 Sean Wheeldon"
description = "Requires Cityscapes. Adds the potential for cities with Cybran structures."
author = "Balthazar"
icon = "/mods/BrewLAN_Plenae/CityGeneration/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
