name = "Hench AF"
uid = "16678e1e-7fc9-11e5-8bcf-x10health0010"
version = 1.0
copyright = "© 2019 Sean Wheeldon"
description = "All units have times 10 health."
author = "Balthazar"
--icon = "/mods/BrewLAN_Gameplay/WaterGuard/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
