name = "Pulchritudinousity"
uid = "BREWLANS-a0a7-426d-88f2-PHOTORZ00003"
version = 0.3
copyright = "© 2015–2020 Sean Wheeldon"
description = "Various tweeks designed for taking better screenshots. Not advised for real gameplay."
author = "Balthazar"
icon = "/mods/BrewLAN_Plenae/Pulchritudinousity/canon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }
