name = "BrewLAN: Bletchley Park"
uid = "25D57D85-9JA7-D842-BREW-INTEL00000002"
version = 2
copyright = "© 2018–2020 Sean Wheeldon"
description = "Adds additional intelligence options."
author = "Balthazar"
--icon = "/mods/BrewLAN_Units/BrewShields/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
