name = "BrewLAN: Magnum Dong"
uid = "25D57D85-9JA7-D842-BREW-MAGNUMD000002"
version = 2
copyright = "© 2018–2021 Sean Wheeldon"
description = "Adds a Cybran experimental mobile artillery."
author = "Balthazar"
icon = "/mods/BrewLAN_Units/BrewMonsters/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
