--ISO_639-1_code=IT
--Translated by: Google
seb2101_name="DMX Riot Gun"
seb2101_desc="Punto luce Difesa"
Unit_Description_TeaD_001="Luce torretta difensiva efficiente. Equipaggiato con una pistola sommossa."

seb3101_name="SA0 - 100"
seb3101_desc="Light System Radar"
Unit_Description_TeaD_002="torre radar luce. Può rivelare la posizione delle unità invisibili."

Unit_Description_TeaD_003="Costruisce unità mobili."

tec0001_desc="Macchina"
tec0002_desc="Camion"
tec0003_desc="Autobus"
tec0004_desc="esploratore"
tec0005_desc="Scudo"
tec0006_desc="Bicicletta"
tec0007_desc="Shield Marine"
tec0008_desc="Cloaked Car"
tec0009_desc="Air Scout"
tec0010_desc="Ambulanza"
tec0011_desc="Grande Aircraft"
tec0012_desc="schermato Aircraft"
tec0101_desc="Gatling Boss"
tec0102_desc="serbatoio Boss"
tec0103_desc="Schermato Boss Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="In attesa di no-fretta di end"
tead_pathfinder_wave="onda Pathfinder"
tead_wave1="Wave Group 1"
tead_DTwave1="Danno prova onda 1"
tead_wave2="Wave Group 2"
tead_warn_cloak="Attenzione: Cloaked unità in entrata"
tead_DTwave2="Danno prova onda 2"
tead_warn_fliers="Attenzione: Fliers in entrata"
tead_wave3="gruppo Wave 3"
tead_boss1="Capo onda 1"
tead_wave4="Wave Group 4"
tead_boss_final="Boss finale"

--stringhe Tead Lobby EN-US
TeaD_Endless_LOB="Tead: modalità Endless"
TeaD_Endless_LOB_D="Mentre le onde enabled in loop con gli appassionati."
TeaD_Endless_LOB_false="Disabilitato"
TeaD_Endless_LOB_falseD="estremità gioco dopo boss finale onda come di consueto."
TeaD_Endless_LOB_true="Abilitato"
TeaD_Endless_LOB_trueD="Gioco loop fino a quando i giocatori muoiono."
TeaD_LOB_Endless_T="Tead modalità infinite onde."
TeaD_LOB_Endless_D="While onde attivare volontà, con appassionati incrementali applicato con ogni reset."
TeaD_LOB_Endless_falseT="onde senza fine disattivate."
TeaD_LOB_Endless_falseD="estremità gioco dopo l'ultima ondata è sconfitto."
TeaD_LOB_Endless_trueT="onde senza fine abilitati."
TeaD_LOB_Endless_trueD="La vittoria è impossibile. Gioco funziona finché non si è alla fine sconfitto."