--ISO_639-1_code=IT
--Translated by: Google
seb2101_name="DMX Riot Gun."
seb2101_desc="La difesa del punto di luce"
Unit_Description_TeaD_001="Torretta difensiva leggera efficiente. Dotato di una pistola antisommossa."

seb3101_name="SA0 - 100."
seb3101_desc="Sistema radar leggero"
Unit_Description_TeaD_002="Torre del radar leggero. Può rivelare le posizioni delle unità invisibili."

Unit_Description_TeaD_003="Costruisce unità mobili."

tec0001_desc="Auto"
tec0002_desc="Camion"
tec0003_desc="Autobus"
tec0004_desc="Pathfinder."
tec0005_desc="Scudo"
tec0006_desc="Bicicletta"
tec0007_desc="Scudo Marine."
tec0008_desc="Auto ammantata"
tec0009_desc="Air scout."
tec0010_desc="Ambulanza"
tec0011_desc="Big Aircraft."
tec0012_desc="Aeromobili schermati"
tec0101_desc="Boss Gatling."
tec0102_desc="Boss del carro armato"
tec0103_desc="Boss Bod Scurso"
tec0104_desc="Big Boss Bot."

tead_waiting_for_no_rush="Aspettando no-Rush di finire"
tead_pathfinder_wave="Pathfinder Wave."
tead_wave1="Gruppo Wave 1."
tead_DTwave1="Danni Test Wave 1"
tead_wave2="Gruppo Wave 2."
tead_warn_cloak="Avvertenza: unità ammantate in entrata"
tead_DTwave2="Danni Test Wave 2"
tead_warn_fliers="Attenzione: volantini in entrata"
tead_wave3="Gruppo Wave 3."
tead_boss1="Boss Wave 1."
tead_wave4="Gruppo Wave 4."
tead_boss_final="Capo finale"

--Tead Lobby EN-US Strings
TeaD_Endless_LOB="TEAD: modalità infinita"
TeaD_Endless_LOB_D="Mentre abilitato le onde loop con gli appassionati di bufari."
TeaD_Endless_LOB_false="Disabilitato"
TeaD_Endless_LOB_falseD="Il gioco termina dopo il capo finale onda come normale."
TeaD_Endless_LOB_true="Abilitato"
TeaD_Endless_LOB_trueD="Loop di gioco fino a quando i giocatori muoiono."
TeaD_LOB_Endless_T="Tead Endless Waves Mode."
TeaD_LOB_Endless_D="Sebbene le onde abilitate loop, con buff incrementali applicati con ciascun reset."
TeaD_LOB_Endless_falseT="Onde infinite disabilitate."
TeaD_LOB_Endless_falseD="Il gioco termina dopo che l'ultima ondata è sconfitta."
TeaD_LOB_Endless_trueT="Onde infinite abilitate."
TeaD_LOB_Endless_trueD="La vittoria è impossibile. Il gioco funziona fino a quando non sei alla fine sconfitto."
