name = "BrewUI"
uid = "25D57D85-7D84-27HT-A501-BR3WUI0000003"
version = 0.3
copyright = "© 2009–2018 Sean Wheeldon"
description = "BrewLAN engineer tab. Dormant without BrewLAN. May conflict with mods with a \"/hook/lua/ui/game/avatars.lua\" file while BrewLAN is active."
author = "Balthazar"
icon = "/mods/BrewLAN_Modules/BrewUI/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = true
conflicts = {  }
before = {  }
after = {  }
