--ISO_639-1_code=DE
--Translated by: Google
seb2101_name="DMX Riot Gun"
seb2101_desc="Lichtpunkt Defense"
Unit_Description_TeaD_001="Light efficient defensiver Turm. Ausgestattet mit einem Aufruhr gun."

seb3101_name="SA0 - 100"
seb3101_desc="Licht-Radar-System"
Unit_Description_TeaD_002="Lichtradarturm. Kann die Standorte der unsichtbaren Einheiten offenbaren."

Unit_Description_TeaD_003="Konstruiert mobile Einheiten."

tec0001_desc="Auto"
tec0002_desc="LKW"
tec0003_desc="Bus"
tec0004_desc="Pfadfinder"
tec0005_desc="Schild"
tec0006_desc="Fahrrad"
tec0007_desc="Schild Meer"
tec0008_desc="verhüllte Auto"
tec0009_desc="Air Scout"
tec0010_desc="Krankenwagen"
tec0011_desc="große Flugzeuge"
tec0012_desc="Shielded Aircraft"
tec0101_desc="Gatling Boss"
tec0102_desc="Behälter-Chef"
tec0103_desc="Shielded Boss Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Warten auf nicht-rush zu beenden"
tead_pathfinder_wave="Pathfinder Welle"
tead_wave1="Wave-Gruppe 1"
tead_DTwave1="Schaden Testwelle 1"
tead_wave2="Wave-Gruppe 2"
tead_warn_cloak="Achtung: Getarnte Einheiten Inbound"
tead_DTwave2="Schaden Testwelle 2"
tead_warn_fliers="Achtung: Fliers Inbound"
tead_wave3="Wave-Gruppe 3"
tead_boss1="Boss Welle 1"
tead_wave4="Wave-Gruppe 4"
tead_boss_final="Endgegner"