--ISO_639-1_code=DE
--Translated by: Binary
seb2101_name="DMX Riot Gun"
seb2101_desc="Leichte Punktverteidigung"
Unit_Description_TeaD_001="Leichter, effizienter, defensiver Turm. Ausgestattet mit einer Riot-Waffe."

seb3101_name="SA0 - 100"
seb3101_desc="Leichtes Radarsystem"
Unit_Description_TeaD_002="Leichter Radarturm. Kann die Standorte unsichtbarer Einheiten offenbaren."

Unit_Description_TeaD_003="Konstruiert mobile Einheiten."

tec0001_desc="Auto"
tec0002_desc="LKW"
tec0003_desc="Bus"
tec0004_desc="Pfadfinder"
tec0005_desc="Schild"
tec0006_desc="Fahrrad"
tec0007_desc="Abgeschirmter Marine"
tec0008_desc="Getarntes Auto"
tec0009_desc="Luftaufklärer"
tec0010_desc="Krankenwagen"
tec0011_desc="Großes Flugzeug"
tec0012_desc="Abgschirmtes Flugzeug"
tec0101_desc="Gatling Boss"
tec0102_desc="Tank Boss"
tec0103_desc="Abgeschirmter Boss-Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Bis zum Ende der Nichtangriffszeit warten"
tead_pathfinder_wave="Pfadfinder Welle"
tead_wave1="Wellengruppe 1"
tead_DTwave1="Schaden der Testwelle 1"
tead_wave2="Wellengruppe 2"
tead_warn_cloak="Achtung: Eine getarnte Einheit nähert sich"
tead_DTwave2="Schaden der Testwelle 2"
tead_warn_fliers="Warnung: Eingehende Flieger"
tead_wave3="Wellengruppe 3"
tead_boss1="Boss Welle 1"
tead_wave4="Wellengruppe 4"
tead_boss_final="Endgegner"

--Translated by: Binary
TeaD_Endless_LOB="TeaD: Endloser Modus"
TeaD_Endless_LOB_D="Wenn aktiviert erhalten wiederkehrende Wellen Boni."
TeaD_Endless_LOB_false="Deaktiviert"
TeaD_Endless_LOB_falseD="Das Spiel endet nach der letzten Bosswelle."
TeaD_Endless_LOB_true="aktiviert"
TeaD_Endless_LOB_trueD="Das Spiel wiederholt sich bis der Spieler stirbt"
TeaD_LOB_Endless_T="TeaD Endloser Wellen Modus."
TeaD_LOB_Endless_D="Wenn aktiviert, Wellen wiederholen sich, mit Boni bei jeder Wiederholung."
TeaD_LOB_Endless_falseT="Endlose Wellen deaktiviert."
TeaD_LOB_Endless_falseD="Das Spiel endet, nachdem die letzte Welle besiegt ist."
TeaD_LOB_Endless_trueT="Endlose Wellen aktiviert."
TeaD_LOB_Endless_trueD="Der Sieg ist unmöglich. Das Spiel läuft, bis Du schließlich besiegt bist."
