name = "BrewLAN: Cursed mods"
uid = "190261d0-4bb0-11e2-bcSC-BLCURSED0001"
version = 1
copyright = "© 2016–2021 Sean Wheeldon"
description = "Container for cursed mods."
author = "Balthazar"
icon = "/mods/BrewLAN_Cursed/folder.png"
selectable = false
enabled = false
