name = "WreckageDecay"
uid = "16678e1e-7fc9-11e5-8bcf-wreckageA01"
version = 0.1
copyright = "© 2019 Sean Wheeldon"
description = "Wrecks disappear after a time that scales with tech level and value. The largest few stay forever."
author = "Balthazar"
--icon =
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
