name = "Paragon Game"
uid = "BREWLANS-22b4-4936-820e-PARAGON0005"
version = 0.5
copyright = "2012 - 2014 Sean Wheeldon"
description = "Player 8 gets a Paragon and a SACU. Only they can build new Paragons and can always build one, regardless of race. Team up appropriately."
author = "Sean Wheeldon"
icon = "/mods/ParagonGame/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { "6EAA2403-27A8-47ee-B4DF-5017E056E501" }
before = { }
after = { }
