--ISO_639-1_code=EN
--Tea Party strings
CityscapesSpawn_LOB="Cityscapes: Player Slots"
CityscapesSpawn_LOB_D="Defines which player spawn locations cities can spawn at."
CityscapesSpawn_LOB_EmptySpots="Empty slots"
CityscapesSpawn_LOB_EmptySpotsD="Cities can spawn in empty player spawn locations."
CityscapesSpawn_LOB_AllSlots="All slots"
CityscapesSpawn_LOB_AllSlotsD="Cities can spawn in any player spawn location."
CityscapesSpawn_LOB_OccupiedSlots="Occupied slots"
CityscapesSpawn_LOB_OccupiedSlotsD="Cities can spawn around players."
CityscapesSpawn_LOB_false="No Slots"
CityscapesSpawn_LOB_falseD="Cities won't spawn at player spawn location."

CityscapesTeam_LOB="Cityscapes: Player Slot Team"
CityscapesTeam_LOB_D="Defines the owner of cities spawned in occupied slots, if they exist."
CityscapesTeam_LOB_Civilian="Civilian"
CityscapesTeam_LOB_CivilianD="Cities in occupied slots are civilian controlled."
CityscapesTeam_LOB_LocalArmy="Local Army"
CityscapesTeam_LOB_CivilianD="Cities in occupied slots are controlled by that army."

CityscapesExpansion_LOB="Cityscapes: Expansion Zones"
CityscapesExpansion_LOB_D="Determines if cities spawn at expansion zones markers."
CityscapesExpansion_LOB_Enabled="Enabled"
CityscapesExpansion_LOB_EnabledD="Civilian cities spawn at expansion markers."
CityscapesExpansion_LOB_Disabled="Disabled"
CityscapesExpansion_LOB_DisabledD="No cities spawn at expansion markers."

CityscapesLargeExpansion_LOB="Cityscapes: Large Expansion Zones"
CityscapesLargeExpansion_LOB_D="Determines if cities spawn at any large expansion zones markers."
CityscapesLargeExpansion_LOB_Enabled="Enabled"
CityscapesLargeExpansion_LOB_EnabledD="Civilian cities spawn at large expansion markers."
CityscapesLargeExpansion_LOB_Disabled="Disabled"
CityscapesLargeExpansion_LOB_DisabledD="No cities spawn at large expansion markers."

CityscapesObjective_LOB="Cityscapes: Objective Markers"
CityscapesObjective_LOB_D="Determines if cities spawn at any Objective markers."
CityscapesObjective_LOB_Enabled="Enabled"
CityscapesObjective_LOB_EnabledD="Civilian cities spawn at objective markers."
CityscapesObjective_LOB_Disabled="Disabled"
CityscapesObjective_LOB_DisabledD="No cities spawn at objective markers."
