name = "Corrosive Ocean"
uid = "BREWLANS-22b4-4936-820e-acid00000000"
version = 0.0
copyright = "� 2018 Sean Wheeldon"
description = "Bodies of water deal damage over time."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_Gameplay/AcidPools/Corrosive.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
