--ISO_639-1_code=EN
--TeaD EN-US strings
seb2101_name="DMX Riot Gun"
seb2101_desc="Light Point Defense"
Unit_Description_TeaD_001="Light efficient defensive turret. Equipped with a riot gun."

seb3101_name="SA0 - 100"
seb3101_desc="Light Radar System"
Unit_Description_TeaD_002="Light radar tower. Can reveal the locations of invisible units."

Unit_Description_TeaD_003="Constructs mobile units."

tec0001_desc="Car"
tec0002_desc="Truck"
tec0003_desc="Bus"
tec0004_desc="Pathfinder"
tec0005_desc="Shield"
tec0006_desc="Bike"
tec0007_desc="Shield Marine"
tec0008_desc="Cloaked Car"
tec0009_desc="Air Scout"
tec0010_desc="Ambulance"
tec0011_desc="Big Aircraft"
tec0012_desc="Shielded Aircraft"
tec0101_desc="Gatling Boss"
tec0102_desc="Tank Boss"
tec0103_desc="Shielded Boss Bot"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="Waiting for no-rush to end"
tead_pathfinder_wave="Pathfinder wave"
tead_wave1="Wave group 1"
tead_DTwave1="Damage test wave 1"
tead_wave2="Wave group 2"
tead_warn_cloak="Warning: Cloaked units inbound"
tead_DTwave2="Damage test wave 2"
tead_warn_fliers="Warning: Fliers inbound"
tead_wave3="Wave group 3"
tead_boss1="Boss wave 1"
tead_wave4="Wave group 4"
tead_boss_final="Final Boss"