--ISO_639-1_code=ZH
--Translated by: YuchenJimmy
CityscapesSpawn_LOB="城市景觀:玩家欄位"
CityscapesSpawn_LOB_D="設定哪些欄位可生成城市"
CityscapesSpawn_LOB_EmptySpots="空欄位"
CityscapesSpawn_LOB_EmptySpotsD="在所有空位產生城市"
CityscapesSpawn_LOB_AllSlots="所有欄位"
CityscapesSpawn_LOB_AllSlotsD="在所有重生點產生城市"
CityscapesSpawn_LOB_OccupiedSlots="占用的欄位"
CityscapesSpawn_LOB_OccupiedSlotsD="在所有玩家周圍產生城市"
CityscapesSpawn_LOB_false="不生成"
CityscapesSpawn_LOB_falseD="所有重生點都不會產生城市"

CityscapesTeam_LOB="城市景觀:玩家團隊欄位"
CityscapesTeam_LOB_D="設定城市的掌控權"
CityscapesTeam_LOB_Civilian="平民"
CityscapesTeam_LOB_CivilianD="已被占用的重生點周圍城市會由平民控制"
CityscapesTeam_LOB_LocalArmy="玩家"
CityscapesTeam_LOB_CivilianD="已被占用的重生點周圍城市會由玩家控制"

CityscapesExpansion_LOB="城市景觀:拓展區域"
CityscapesExpansion_LOB_D="確認城市是否正確地在拓展區域生成"
CityscapesExpansion_LOB_Enabled="啟用"
CityscapesExpansion_LOB_EnabledD="平民建築將會在拓展區域生成"
CityscapesExpansion_LOB_Disabled="停用"
CityscapesExpansion_LOB_DisabledD="禁止城市在拓展區域生成"

CityscapesLargeExpansion_LOB="城市景觀:大型拓展區域"
CityscapesLargeExpansion_LOB_D="確認城市是否正確地在大型拓展區域生成"
CityscapesLargeExpansion_LOB_Enabled="啟用"
CityscapesLargeExpansion_LOB_EnabledD="平民建築將會在大型拓展區域生成"
CityscapesLargeExpansion_LOB_Disabled="停用"
CityscapesLargeExpansion_LOB_DisabledD="禁止城市在大型拓展區域生成"

CityscapesObjective_LOB="中立標示"
CityscapesObjective_LOB_D="決定是否在中立標示生成城市"
CityscapesObjective_LOB_Enabled="啟用"
CityscapesObjective_LOB_EnabledD="平民城市將會在中立標示生成"
CityscapesObjective_LOB_Disabled="停用"
CityscapesObjective_LOB_DisabledD="平民城市將不會在中立標示生成"
