--ISO_639-1_code=ZH
--Translated by: Google
CityscapesSpawn_LOB="风情：玩家插槽"
CityscapesSpawn_LOB_D="定义哪个球员产卵地点的城市可在产卵。"
CityscapesSpawn_LOB_EmptySpots="空槽"
CityscapesSpawn_LOB_EmptySpotsD="城市在空机产卵地点产卵。"
CityscapesSpawn_LOB_AllSlots="所有插槽"
CityscapesSpawn_LOB_AllSlotsD="城市可以在任何球员产卵地点产卵。"
CityscapesSpawn_LOB_OccupiedSlots="所占用的时隙"
CityscapesSpawn_LOB_OccupiedSlotsD="城市可以产卵各地的玩家。"
CityscapesSpawn_LOB_false="没有插槽"
CityscapesSpawn_LOB_falseD="城市不会在球员产卵地点产卵。"

CityscapesTeam_LOB="风情：球员老虎队"
CityscapesTeam_LOB_D="定义中所占用的时隙催生，如果它们存在的城市的主人。"
CityscapesTeam_LOB_Civilian="平民"
CityscapesTeam_LOB_CivilianD="在占用时隙城市平民的控制。"
CityscapesTeam_LOB_LocalArmy="当地军"
CityscapesTeam_LOB_CivilianD="在占用时隙的城市是由军队控制。"

CityscapesExpansion_LOB="风情：扩展区"
CityscapesExpansion_LOB_D="确定是否在城市扩张的区域的标记产卵。"
CityscapesExpansion_LOB_Enabled="启用"
CityscapesExpansion_LOB_EnabledD="平民城市产卵在扩展标记。"
CityscapesExpansion_LOB_Disabled="残"
CityscapesExpansion_LOB_DisabledD="没有城市在扩展标记产卵。"

CityscapesLargeExpansion_LOB="城市景观：大扩展区"
CityscapesLargeExpansion_LOB_D="确定是否在城市的任何大的扩展区标志产卵。"
CityscapesLargeExpansion_LOB_Enabled="启用"
CityscapesLargeExpansion_LOB_EnabledD="平民在城市化扩张的标记产卵。"
CityscapesLargeExpansion_LOB_Disabled="残"
CityscapesLargeExpansion_LOB_DisabledD="没有城市在大规模扩张的标记产卵。"

CityscapesObjective_LOB="风情：目的标记"
CityscapesObjective_LOB_D="确定是否在城市的任何目的的标记产卵。"
CityscapesObjective_LOB_Enabled="启用"
CityscapesObjective_LOB_EnabledD="平民城市在客观指标产卵。"
CityscapesObjective_LOB_Disabled="残"
CityscapesObjective_LOB_DisabledD="没有城市在客观指标产卵。"