--ISO_639-1_code=FR
--Translated by: Google
seb2101_name="DMX Riot Gun"
seb2101_desc="Point Light Défense"
Unit_Description_TeaD_001="Lumière tourelle de défense efficace. Equipé d'une arme anti-émeute."

seb3101_name="SA0 - 100"
seb3101_desc="Light System Radar"
Unit_Description_TeaD_002="Vérine radar. Peut révéler les emplacements des unités invisibles."

Unit_Description_TeaD_003="Unités mobiles construit."

tec0001_desc="Voiture"
tec0002_desc="un camion"
tec0003_desc="Autobus"
tec0004_desc="Éclaireur"
tec0005_desc="Bouclier"
tec0006_desc="Bicyclette"
tec0007_desc="Bouclier Marine"
tec0008_desc="Cloaked voiture"
tec0009_desc="air scout"
tec0010_desc="Ambulance"
tec0011_desc="Big Aircraft"
tec0012_desc="Aéronefs Shielded"
tec0101_desc="Gatling patron"
tec0102_desc="réservoir patron"
tec0103_desc="Patron Bot Shielded"
tec0104_desc="Big Boss Bot"

tead_waiting_for_no_rush="En attendant sans course à la fin"
tead_pathfinder_wave="onde Pathfinder"
tead_wave1="Wave Group 1"
tead_DTwave1="onde test Dommages 1"
tead_wave2="Wave Group 2"
tead_warn_cloak="Attention: les unités camouflées entrants"
tead_DTwave2="onde test de dommages 2"
tead_warn_fliers="Avertissement: Fliers entrant"
tead_wave3="Wave Group 3"
tead_boss1="Patron onde 1"
tead_wave4="Wave Group 4"
tead_boss_final="final boss"

--Tead Lobby chaînes EN-US
TeaD_Endless_LOB="Tead: Mode sans fin"
TeaD_Endless_LOB_D="Alors que les ondes activées en boucle avec les amateurs."
TeaD_Endless_LOB_false="désactivé"
TeaD_Endless_LOB_falseD="jeu se termine après boss final vague comme d'habitude."
TeaD_Endless_LOB_true="Activée"
TeaD_Endless_LOB_trueD="boucles jeu jusqu'à ce que les joueurs meurent."
TeaD_LOB_Endless_T="mode vagues sans fin Tead."
TeaD_LOB_Endless_D="Alors que la boucle des ondes permis de volonté, avec buffs supplémentaires appliqués à chaque remise à zéro."
TeaD_LOB_Endless_falseT="vagues sans fin désactivées."
TeaD_LOB_Endless_falseD="jeu se termine après la dernière vague est vaincu."
TeaD_LOB_Endless_trueT="vagues sans fin activées."
TeaD_LOB_Endless_trueD="La victoire est impossible. Jeu court jusqu'à ce que vous êtes finalement vaincu."