--ISO_639-1_code=FR
--Translated by: Markty_07, Google
seb2101_name="DMX Arme Anti Émeute"
seb2101_desc="Pointe de Défense légère"
Unit_Description_TeaD_001="Tourelle défensive légère et efficace. Équipée d'une arme anti-émeute."

seb3101_name="SA0 - 100"
seb3101_desc="Système de Radar Léger"
Unit_Description_TeaD_002="Système de radar léger. Peut révèler la position des unités invisible."

Unit_Description_TeaD_003="Construit des unités mobiles."

tec0001_desc="Auto"
tec0002_desc="Camion"
tec0003_desc="Autobus"
tec0004_desc="Éclaireur"
tec0005_desc="Bouclier"
tec0006_desc="Vélo"
tec0007_desc="Bouclier marin"
tec0008_desc="Voiture à masque"
tec0009_desc="Scout aérien"
tec0010_desc="Ambulance"
tec0011_desc="Gros aéronefs"
tec0012_desc="Avion blindé"
tec0101_desc="Patron de gatling"
tec0102_desc="Citerne"
tec0103_desc="Boss blindé Bot"
tec0104_desc="Gros bot bot"

tead_waiting_for_no_rush="En attente de la fin du temps sans rush"
tead_pathfinder_wave="Onde de localisation de chemin"
tead_wave1="Groupe d'ondes 1"
tead_DTwave1="Vague de test de dommages 1"
tead_wave2="Groupe de vagues 2"
tead_warn_cloak="AVERTISSEMENT: Unités de mastication entrante"
tead_DTwave2="Vague de test de dommages 2"
tead_warn_fliers="AVERTISSEMENT: Flots entrants"
tead_wave3="Groupe d'ondes 3"
tead_boss1="Boss Wave 1"
tead_wave4="Groupe d'ondes 4"
tead_boss_final="Chef final"

--Tead hall en-américain
TeaD_Endless_LOB="Tead: Mode sans fin"
TeaD_Endless_LOB_D="Tandis que les ondes activées vont boucler avec des buffs."
TeaD_Endless_LOB_false="Désactivé"
TeaD_Endless_LOB_falseD="Le jeu se termine après la vague de Boss finale comme normale."
TeaD_Endless_LOB_true="Autorisé"
TeaD_Endless_LOB_trueD="Des boucles de jeu jusqu'à ce que les joueurs meurent."
TeaD_LOB_Endless_T="Tead Endless Waves Mode."
TeaD_LOB_Endless_D="Bien que les ondes activées se bouclent, avec des buffs incrémentiels appliqués à chaque réinitialisation."
TeaD_LOB_Endless_falseT="Ondes sans fin désactivées."
TeaD_LOB_Endless_falseD="Le jeu se termine après la défaite de la dernière vague."
TeaD_LOB_Endless_trueT="Ondes sans fin activées."
TeaD_LOB_Endless_trueD="La victoire est impossible. Le jeu court jusqu'à ce que vous soyez finalement vaincu."
