--ISO_639-1_code=FR
--Translated by: Markty_07
CityscapesSpawn_LOB="Villes : Emplacements des Joueurs"
CityscapesSpawn_LOB_D="Définit à quels point d'apparition des joueurs les villes peuvent apparaitre."
CityscapesSpawn_LOB_EmptySpots="Emplacements vides"
CityscapesSpawn_LOB_EmptySpotsD="Les villes peuvent apparaitre dans les emplacements de départ non-occupés."
CityscapesSpawn_LOB_AllSlots="Tous les emplacements"
CityscapesSpawn_LOB_AllSlotsD="Les villes apparaissent dans tout les emplacements de départ, même si il est occupé par un joueur ou une IA."
CityscapesSpawn_LOB_OccupiedSlots="Emplacements occupés"
CityscapesSpawn_LOB_OccupiedSlotsD="Les villes peuvent apparaitre autour des joueurs."
CityscapesSpawn_LOB_false="Aucun emplacement"
CityscapesSpawn_LOB_falseD="Les villes n'apparaitront pas aux emplacements de départ, qu'ils soient occupés ou non."

CityscapesTeam_LOB="Villes des point de départ des joueurs : équipe"
CityscapesTeam_LOB_D="Définit le propriétaire des villes apparaissant dans des emplacements occupés."
CityscapesTeam_LOB_Civilian="Civil"
CityscapesTeam_LOB_CivilianD="Les villes dans les emplacements occupés sont contrôlés par des civils."
CityscapesTeam_LOB_LocalArmy="Armée locale"
CityscapesTeam_LOB_CivilianD="Les villes dans les emplacements occupés sont contrôlés par cette armée."

CityscapesExpansion_LOB="Villes : Zones d'expansion"
CityscapesExpansion_LOB_D="Détermine si les villes apparaissent au zones d'expansion."
CityscapesExpansion_LOB_Enabled="Activé"
CityscapesExpansion_LOB_EnabledD="Les villes civiles se reproduisent au niveau des marqueurs d'expansion."
CityscapesExpansion_LOB_Disabled="Désactivée"
CityscapesExpansion_LOB_DisabledD="Aucune villes n'apparaissent au niveau des zones d'expansion."

CityscapesLargeExpansion_LOB="Villes : Zones d'Expansion Larges"
CityscapesLargeExpansion_LOB_D="Détermine si les villes apparaissent à n'importe quelle zone d'expansion large."
CityscapesLargeExpansion_LOB_Enabled="Activé"
CityscapesLargeExpansion_LOB_EnabledD="Les villes civiles apparaissent aux large zones d'expansion."
CityscapesLargeExpansion_LOB_Disabled="Désactivée"
CityscapesLargeExpansion_LOB_DisabledD="Aucune ville n'apparait aux large zones d'expansion."

CityscapesObjective_LOB="Villes : Objectifs"
CityscapesObjective_LOB_D="Détermine si le villes apparaissent au niveau des objectifs."
CityscapesObjective_LOB_Enabled="Activé"
CityscapesObjective_LOB_EnabledD="Les villes apparaissent près des objectifs."
CityscapesObjective_LOB_Disabled="Désactivée"
CityscapesObjective_LOB_DisabledD="Aucune ville n'apparait près des objectifs."
