--ISO_639-1_code=FR
--Translated by: Google
CityscapesSpawn_LOB="Machines à sous PAYSAGES URBAINS: Joueur"
CityscapesSpawn_LOB_D="Définit les lieux d'apparition des joueurs villes peuvent frayer à."
CityscapesSpawn_LOB_EmptySpots="fentes vides"
CityscapesSpawn_LOB_EmptySpotsD="Les villes peuvent se reproduire dans des endroits de frai des joueurs vides."
CityscapesSpawn_LOB_AllSlots="tous les emplacements"
CityscapesSpawn_LOB_AllSlotsD="Les villes peuvent se reproduire dans un endroit d'apparition des joueurs."
CityscapesSpawn_LOB_OccupiedSlots="emplacements occupés"
CityscapesSpawn_LOB_OccupiedSlotsD="Les villes peuvent se reproduire autour de joueurs."
CityscapesSpawn_LOB_false="Non Slots"
CityscapesSpawn_LOB_falseD="Les villes ne pondra pas au joueur emplacement de spawn."

CityscapesTeam_LOB="Paysages urbains: Joueur d'équipe Slot"
CityscapesTeam_LOB_D="Définit le propriétaire des villes donné naissance dans les emplacements occupés, si elles existent."
CityscapesTeam_LOB_Civilian="Civil"
CityscapesTeam_LOB_CivilianD="Les villes dans les emplacements occupés sont contrôlés par des civils."
CityscapesTeam_LOB_LocalArmy="Armée locale"
CityscapesTeam_LOB_CivilianD="Les villes dans les emplacements occupés sont contrôlés par cette armée."

CityscapesExpansion_LOB="Paysages urbains: Zones d'extension"
CityscapesExpansion_LOB_D="Détermine si les villes se reproduisent au niveau des zones d'expansion des marqueurs."
CityscapesExpansion_LOB_Enabled="Activée"
CityscapesExpansion_LOB_EnabledD="Les villes civiles se reproduisent au niveau des marqueurs d'expansion."
CityscapesExpansion_LOB_Disabled="désactivé"
CityscapesExpansion_LOB_DisabledD="Aucune ville frayent au niveau des marqueurs d'expansion."

CityscapesLargeExpansion_LOB="Zones: paysages urbains de grande extension"
CityscapesLargeExpansion_LOB_D="Détermine si les villes se reproduisent à toutes les grandes zones d'expansion des marqueurs."
CityscapesLargeExpansion_LOB_Enabled="Activée"
CityscapesLargeExpansion_LOB_EnabledD="Les villes civiles se reproduisent à grands marqueurs d'expansion."
CityscapesLargeExpansion_LOB_Disabled="désactivé"
CityscapesLargeExpansion_LOB_DisabledD="Aucune ville frayent à grands marqueurs d'expansion."

CityscapesObjective_LOB="Objectif: Marqueurs des paysages urbains"
CityscapesObjective_LOB_D="Détermine si les villes se reproduisent à des marqueurs Objectif."
CityscapesObjective_LOB_Enabled="Activée"
CityscapesObjective_LOB_EnabledD="Les villes civiles se reproduisent à des marqueurs objectifs."
CityscapesObjective_LOB_Disabled="désactivé"
CityscapesObjective_LOB_DisabledD="Aucune ville frayent à des marqueurs objectifs."